# coding: utf-8

"""
    Monarch Bridge

    HTTP/JSON wrapper over Monarch Money's GraphQL API.  **Contract conventions:** - Every successful 2xx body is `{\"data\": <typed object>}` (except `/healthz`   and `/v1/auth/{status,refresh}`, which return plain bodies so health probes   stay zero-parse). - Failure bodies, when returned, are `{\"code\": ..., \"message\": ..., \"details\": {...}}`. - Mutations whose application layer reports errors come back as `HTTP 422`   (the proxy walks Monarch's `data.<mutation>.errors[]` and surfaces it). - No per-request auth on the wire - the bridge holds Monarch's session token   itself, loaded once via the interactive bootstrap CLI.  **Source of truth.** This multi-file YAML tree is hand-curated and authoritative. Both request DTOs and response DTOs are generated from it via openapi-generator-gradle-plugin into `build/generated/openapi/`, along with a Spring `*Api` interface per tag that controllers implement directly. The spec drives the web layer end-to-end.  Full agent reference + every Monarch quirk: see `agents/context/AGENTS.md`. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from monarch_bridge_client.models.institution import Institution
from typing import Optional, Set
from typing_extensions import Self

class Account(BaseModel):
    """
    A Monarch account - either Plaid-linked or manually-created.
    """ # noqa: E501
    id: StrictStr = Field(description="Stable Monarch account id.")
    display_name: StrictStr = Field(alias="displayName")
    type: Optional[StrictStr] = Field(default=None, description="Top-level account type (e.g. `depository`, `brokerage`, `credit`).")
    subtype: Optional[StrictStr] = Field(default=None, description="Subtype within the type (e.g. `savings`, `401k`).")
    mask: Optional[StrictStr] = None
    current_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Last-known balance in account currency. May be negative for credit/loan.", alias="currentBalance")
    display_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="displayBalance")
    is_hidden: Optional[StrictBool] = Field(default=None, description="Monarch's legacy hidden flag.", alias="isHidden")
    hide_from_list: Optional[StrictBool] = Field(default=None, description="True if the user has hidden this account from the main list.", alias="hideFromList")
    include_in_net_worth: Optional[StrictBool] = Field(default=None, alias="includeInNetWorth")
    is_asset: Optional[StrictBool] = Field(default=None, alias="isAsset")
    is_manual: Optional[StrictBool] = Field(default=None, description="True for manually-created (non-Plaid) accounts.", alias="isManual")
    institution: Optional[Institution] = None
    __properties: ClassVar[List[str]] = ["id", "displayName", "type", "subtype", "mask", "currentBalance", "displayBalance", "isHidden", "hideFromList", "includeInNetWorth", "isAsset", "isManual", "institution"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Account from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of institution
        if self.institution:
            _dict['institution'] = self.institution.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Account from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "displayName": obj.get("displayName"),
            "type": obj.get("type"),
            "subtype": obj.get("subtype"),
            "mask": obj.get("mask"),
            "currentBalance": obj.get("currentBalance"),
            "displayBalance": obj.get("displayBalance"),
            "isHidden": obj.get("isHidden"),
            "hideFromList": obj.get("hideFromList"),
            "includeInNetWorth": obj.get("includeInNetWorth"),
            "isAsset": obj.get("isAsset"),
            "isManual": obj.get("isManual"),
            "institution": Institution.from_dict(obj["institution"]) if obj.get("institution") is not None else None
        })
        return _obj


