# coding: utf-8

"""
    Monarch Bridge

    HTTP/JSON wrapper over Monarch Money's GraphQL API.  **Contract conventions:** - Every successful 2xx body is `{\"data\": <typed object>}` (except `/healthz`   and `/v1/auth/{status,refresh}`, which return plain bodies so health probes   stay zero-parse). - Failure bodies, when returned, are `{\"code\": ..., \"message\": ..., \"details\": {...}}`. - Mutations whose application layer reports errors come back as `HTTP 422`   (the proxy walks Monarch's `data.<mutation>.errors[]` and surfaces it). - No per-request auth on the wire - the bridge holds Monarch's session token   itself, loaded once via the interactive bootstrap CLI.  **Source of truth.** This multi-file YAML tree is hand-curated and authoritative. Both request DTOs and response DTOs are generated from it via openapi-generator-gradle-plugin into `build/generated/openapi/`, along with a Spring `*Api` interface per tag that controllers implement directly. The spec drives the web layer end-to-end.  Full agent reference + every Monarch quirk: see `agents/context/AGENTS.md`. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CategoryEditFields(BaseModel):
    """
    CategoryEditFields
    """ # noqa: E501
    id: StrictStr
    name: Optional[StrictStr] = None
    order: Optional[StrictInt] = None
    icon: Optional[StrictStr] = None
    system_category: Optional[StrictStr] = Field(default=None, alias="systemCategory")
    system_category_display_name: Optional[StrictStr] = Field(default=None, alias="systemCategoryDisplayName")
    budget_variability: Optional[StrictStr] = Field(default=None, alias="budgetVariability")
    exclude_from_budget: Optional[StrictBool] = Field(default=None, alias="excludeFromBudget")
    is_system_category: Optional[StrictBool] = Field(default=None, alias="isSystemCategory")
    is_disabled: Optional[StrictBool] = Field(default=None, alias="isDisabled")
    is_protected: Optional[StrictBool] = Field(default=None, alias="isProtected")
    group_id: Optional[StrictStr] = Field(default=None, alias="groupId")
    group_type: Optional[StrictStr] = Field(default=None, alias="groupType")
    group_level_budgeting_enabled: Optional[StrictBool] = Field(default=None, alias="groupLevelBudgetingEnabled")
    rollover_period_id: Optional[StrictStr] = Field(default=None, alias="rolloverPeriodId")
    rollover_start_month: Optional[date] = Field(default=None, alias="rolloverStartMonth")
    rollover_starting_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="rolloverStartingBalance")
    rollover_type: Optional[StrictStr] = Field(default=None, alias="rolloverType")
    rollover_frequency: Optional[StrictStr] = Field(default=None, alias="rolloverFrequency")
    rollover_target_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="rolloverTargetAmount")
    __properties: ClassVar[List[str]] = ["id", "name", "order", "icon", "systemCategory", "systemCategoryDisplayName", "budgetVariability", "excludeFromBudget", "isSystemCategory", "isDisabled", "isProtected", "groupId", "groupType", "groupLevelBudgetingEnabled", "rolloverPeriodId", "rolloverStartMonth", "rolloverStartingBalance", "rolloverType", "rolloverFrequency", "rolloverTargetAmount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CategoryEditFields from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CategoryEditFields from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "order": obj.get("order"),
            "icon": obj.get("icon"),
            "systemCategory": obj.get("systemCategory"),
            "systemCategoryDisplayName": obj.get("systemCategoryDisplayName"),
            "budgetVariability": obj.get("budgetVariability"),
            "excludeFromBudget": obj.get("excludeFromBudget"),
            "isSystemCategory": obj.get("isSystemCategory"),
            "isDisabled": obj.get("isDisabled"),
            "isProtected": obj.get("isProtected"),
            "groupId": obj.get("groupId"),
            "groupType": obj.get("groupType"),
            "groupLevelBudgetingEnabled": obj.get("groupLevelBudgetingEnabled"),
            "rolloverPeriodId": obj.get("rolloverPeriodId"),
            "rolloverStartMonth": obj.get("rolloverStartMonth"),
            "rolloverStartingBalance": obj.get("rolloverStartingBalance"),
            "rolloverType": obj.get("rolloverType"),
            "rolloverFrequency": obj.get("rolloverFrequency"),
            "rolloverTargetAmount": obj.get("rolloverTargetAmount")
        })
        return _obj


