# coding: utf-8

"""
    Monarch Bridge

    HTTP/JSON wrapper over Monarch Money's GraphQL API.  **Contract conventions:** - Every successful 2xx body is `{\"data\": <typed object>}` (except `/healthz`   and `/v1/auth/{status,refresh}`, which return plain bodies so health probes   stay zero-parse). - Failure bodies, when returned, are `{\"code\": ..., \"message\": ..., \"details\": {...}}`. - Mutations whose application layer reports errors come back as `HTTP 422`   (the proxy walks Monarch's `data.<mutation>.errors[]` and surfaces it). - No per-request auth on the wire - the bridge holds Monarch's session token   itself, loaded once via the interactive bootstrap CLI.  **Source of truth.** This multi-file YAML tree is hand-curated and authoritative. Both request DTOs and response DTOs are generated from it via openapi-generator-gradle-plugin into `build/generated/openapi/`, along with a Spring `*Api` interface per tag that controllers implement directly. The spec drives the web layer end-to-end.  Full agent reference + every Monarch quirk: see `agents/context/AGENTS.md`. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Goal(BaseModel):
    """
    A v2 savings goal.
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    type: Optional[StrictStr] = Field(default=None, description="One of `savings`, `debt`.")
    status: Optional[StrictStr] = Field(default=None, description="Lifecycle status (`active`, `complete`, `archived`, etc.).")
    progress: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="0.0 → 1.0 fraction of `targetAmount` reached.")
    current_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="currentBalance")
    target_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="targetAmount")
    target_date: Optional[StrictStr] = Field(default=None, description="ISO date the user is aiming for (`YYYY-MM-DD`); nullable for open-ended goals.", alias="targetDate")
    archived_at: Optional[StrictStr] = Field(default=None, description="ISO timestamp the goal was archived; null for active goals.", alias="archivedAt")
    created_at: Optional[StrictStr] = Field(default=None, alias="createdAt")
    priority: Optional[StrictInt] = Field(default=None, description="User-set ordering (lower = higher priority).")
    is_sinking_fund: Optional[StrictBool] = Field(default=None, alias="isSinkingFund")
    planned_monthly_contribution: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="plannedMonthlyContribution")
    estimated_months_until_completion: Optional[StrictInt] = Field(default=None, alias="estimatedMonthsUntilCompletion")
    forecasted_completion_date: Optional[StrictStr] = Field(default=None, alias="forecastedCompletionDate")
    image_storage_provider: Optional[StrictStr] = Field(default=None, alias="imageStorageProvider")
    image_storage_provider_id: Optional[StrictStr] = Field(default=None, alias="imageStorageProviderId")
    __properties: ClassVar[List[str]] = ["id", "name", "type", "status", "progress", "currentBalance", "targetAmount", "targetDate", "archivedAt", "createdAt", "priority", "isSinkingFund", "plannedMonthlyContribution", "estimatedMonthsUntilCompletion", "forecastedCompletionDate", "imageStorageProvider", "imageStorageProviderId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Goal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Goal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "progress": obj.get("progress"),
            "currentBalance": obj.get("currentBalance"),
            "targetAmount": obj.get("targetAmount"),
            "targetDate": obj.get("targetDate"),
            "archivedAt": obj.get("archivedAt"),
            "createdAt": obj.get("createdAt"),
            "priority": obj.get("priority"),
            "isSinkingFund": obj.get("isSinkingFund"),
            "plannedMonthlyContribution": obj.get("plannedMonthlyContribution"),
            "estimatedMonthsUntilCompletion": obj.get("estimatedMonthsUntilCompletion"),
            "forecastedCompletionDate": obj.get("forecastedCompletionDate"),
            "imageStorageProvider": obj.get("imageStorageProvider"),
            "imageStorageProviderId": obj.get("imageStorageProviderId")
        })
        return _obj


