# coding: utf-8

"""
    Monarch Bridge

    HTTP/JSON wrapper over Monarch Money's GraphQL API.  **Contract conventions:** - Every successful 2xx body is `{\"data\": <typed object>}` (except `/healthz`   and `/v1/auth/{status,refresh}`, which return plain bodies so health probes   stay zero-parse). - Failure bodies, when returned, are `{\"code\": ..., \"message\": ..., \"details\": {...}}`. - Mutations whose application layer reports errors come back as `HTTP 422`   (the proxy walks Monarch's `data.<mutation>.errors[]` and surfaces it). - No per-request auth on the wire - the bridge holds Monarch's session token   itself, loaded once via the interactive bootstrap CLI.  **Source of truth.** This multi-file YAML tree is hand-curated and authoritative. Both request DTOs and response DTOs are generated from it via openapi-generator-gradle-plugin into `build/generated/openapi/`, along with a Spring `*Api` interface per tag that controllers implement directly. The spec drives the web layer end-to-end.  Full agent reference + every Monarch quirk: see `agents/context/AGENTS.md`. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from monarch_bridge_client.models.merchant_ref import MerchantRef
from monarch_bridge_client.models.ref import Ref
from monarch_bridge_client.models.tag_ref import TagRef
from monarch_bridge_client.models.transaction_account_ref import TransactionAccountRef
from typing import Optional, Set
from typing_extensions import Self

class Transaction(BaseModel):
    """
    A Monarch transaction.
    """ # noqa: E501
    id: StrictStr
    var_date: date = Field(alias="date")
    amount: Union[StrictFloat, StrictInt] = Field(description="Signed. Negative = expense, positive = income.")
    pending: Optional[StrictBool] = None
    plaid_name: Optional[StrictStr] = Field(default=None, alias="plaidName")
    notes: Optional[StrictStr] = None
    hide_from_reports: Optional[StrictBool] = Field(default=None, alias="hideFromReports")
    needs_review: Optional[StrictBool] = Field(default=None, alias="needsReview")
    is_recurring: Optional[StrictBool] = Field(default=None, alias="isRecurring")
    is_split_transaction: Optional[StrictBool] = Field(default=None, alias="isSplitTransaction")
    created_at: Optional[StrictStr] = Field(default=None, alias="createdAt")
    updated_at: Optional[StrictStr] = Field(default=None, alias="updatedAt")
    account: Optional[TransactionAccountRef] = None
    merchant: Optional[MerchantRef] = None
    category: Optional[Ref] = None
    tags: Optional[List[TagRef]] = None
    __properties: ClassVar[List[str]] = ["id", "date", "amount", "pending", "plaidName", "notes", "hideFromReports", "needsReview", "isRecurring", "isSplitTransaction", "createdAt", "updatedAt", "account", "merchant", "category", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Transaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of merchant
        if self.merchant:
            _dict['merchant'] = self.merchant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of category
        if self.category:
            _dict['category'] = self.category.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Transaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "date": obj.get("date"),
            "amount": obj.get("amount"),
            "pending": obj.get("pending"),
            "plaidName": obj.get("plaidName"),
            "notes": obj.get("notes"),
            "hideFromReports": obj.get("hideFromReports"),
            "needsReview": obj.get("needsReview"),
            "isRecurring": obj.get("isRecurring"),
            "isSplitTransaction": obj.get("isSplitTransaction"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "account": TransactionAccountRef.from_dict(obj["account"]) if obj.get("account") is not None else None,
            "merchant": MerchantRef.from_dict(obj["merchant"]) if obj.get("merchant") is not None else None,
            "category": Ref.from_dict(obj["category"]) if obj.get("category") is not None else None,
            "tags": [TagRef.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None
        })
        return _obj


