/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.nicholasklaene.monarchbridge.client.models.ContributeToGoalResponse
import com.nicholasklaene.monarchbridge.client.models.ContributeToGoalRequest
import com.nicholasklaene.monarchbridge.client.models.CreateGoalResponse
import com.nicholasklaene.monarchbridge.client.models.CreateGoalRequest
import com.nicholasklaene.monarchbridge.client.models.GetGoalContributionHistoryResponse
import com.nicholasklaene.monarchbridge.client.models.GetGoalProjectionResponse
import com.nicholasklaene.monarchbridge.client.models.GetGoalsCurrentMonthTotalsResponse
import com.nicholasklaene.monarchbridge.client.models.HardDeleteGoalResponse
import com.nicholasklaene.monarchbridge.client.models.LinkTransactionToGoalResponse
import com.nicholasklaene.monarchbridge.client.models.LinkTransactionToGoalRequest
import com.nicholasklaene.monarchbridge.client.models.ListGoalEventsResponse
import com.nicholasklaene.monarchbridge.client.models.ListGoalsResponse
import com.nicholasklaene.monarchbridge.client.models.MarkGoalCompleteResponse
import com.nicholasklaene.monarchbridge.client.models.MarkTransactionStreamAsNotRecurringResponse
import com.nicholasklaene.monarchbridge.client.models.RequestRefresh503Response
import com.nicholasklaene.monarchbridge.client.models.SetGoalBudgetAmountRequest
import com.nicholasklaene.monarchbridge.client.models.SpendFromGoalResponse
import com.nicholasklaene.monarchbridge.client.models.SpendFromGoalRequest
import com.nicholasklaene.monarchbridge.client.models.UpdateGoalRequest
import com.nicholasklaene.monarchbridge.client.models.UpdateGoalsPrioritiesResponse
import com.nicholasklaene.monarchbridge.client.models.UpdateGoalsPrioritiesRequest
import com.nicholasklaene.monarchbridge.client.models.WithdrawFromGoalResponse
import com.nicholasklaene.monarchbridge.client.models.WithdrawFromGoalRequest

import com.squareup.moshi.Json

import com.nicholasklaene.monarchbridge.client.infrastructure.ApiClient
import com.nicholasklaene.monarchbridge.client.infrastructure.ApiResponse
import com.nicholasklaene.monarchbridge.client.infrastructure.ClientException
import com.nicholasklaene.monarchbridge.client.infrastructure.ClientError
import com.nicholasklaene.monarchbridge.client.infrastructure.ServerException
import com.nicholasklaene.monarchbridge.client.infrastructure.ServerError
import com.nicholasklaene.monarchbridge.client.infrastructure.MultiValueMap
import com.nicholasklaene.monarchbridge.client.infrastructure.PartConfig
import com.nicholasklaene.monarchbridge.client.infrastructure.RequestConfig
import com.nicholasklaene.monarchbridge.client.infrastructure.RequestMethod
import com.nicholasklaene.monarchbridge.client.infrastructure.ResponseType
import com.nicholasklaene.monarchbridge.client.infrastructure.Success
import com.nicholasklaene.monarchbridge.client.infrastructure.toMultiValue

class GoalsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:9084")
        }
    }

    /**
     * DELETE /v1/goals/{id}
     * Archive a savings goal
     * **Soft-deletes** the goal by setting its &#x60;archivedAt&#x60; timestamp. The goal remains visible via &#x60;GET /v1/goals&#x60; (filter on &#x60;archivedAt&#x60; to hide) but its &#x60;status&#x60; flips to &#x60;archived&#x60; and it drops out of active-goal aggregates.  Reversible via &#x60;POST /v1/goals/{id}/unarchive&#x60;. For permanent removal use &#x60;DELETE /v1/goals/{id}/hard&#x60; instead. 
     * @param id Monarch savings-goal id.
     * @return CreateGoalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun archiveGoal(id: kotlin.String) : CreateGoalResponse {
        val localVarResponse = archiveGoalWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateGoalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/goals/{id}
     * Archive a savings goal
     * **Soft-deletes** the goal by setting its &#x60;archivedAt&#x60; timestamp. The goal remains visible via &#x60;GET /v1/goals&#x60; (filter on &#x60;archivedAt&#x60; to hide) but its &#x60;status&#x60; flips to &#x60;archived&#x60; and it drops out of active-goal aggregates.  Reversible via &#x60;POST /v1/goals/{id}/unarchive&#x60;. For permanent removal use &#x60;DELETE /v1/goals/{id}/hard&#x60; instead. 
     * @param id Monarch savings-goal id.
     * @return ApiResponse<CreateGoalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun archiveGoalWithHttpInfo(id: kotlin.String) : ApiResponse<CreateGoalResponse?> {
        val localVariableConfig = archiveGoalRequestConfig(id = id)

        return request<Unit, CreateGoalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation archiveGoal
     *
     * @param id Monarch savings-goal id.
     * @return RequestConfig
     */
    fun archiveGoalRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/goals/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/goals/{id}/contributions
     * Record a contribution to a savings goal
     * Logs a contribution event against a goal from a specific account. Required: &#x60;accountId&#x60; and &#x60;amount&#x60; (in dollars, positive for a contribution, negative for a withdrawal). &#x60;date&#x60; defaults to today if omitted.  Use after a manual transfer the user wants attributed to the goal, or to backfill historical progress. Updates the goal&#39;s &#x60;currentAmount&#x60; and appends to its event log (visible via &#x60;GET /v1/goals/{id}/events&#x60;).  Distinct from &#x60;PUT /v1/goals/{id}/budget&#x60; which sets the planned monthly contribution (forecast) rather than logging an actual one. 
     * @param id Monarch savings-goal id.
     * @param contributeToGoalRequest 
     * @return ContributeToGoalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun contributeToGoal(id: kotlin.String, contributeToGoalRequest: ContributeToGoalRequest) : ContributeToGoalResponse {
        val localVarResponse = contributeToGoalWithHttpInfo(id = id, contributeToGoalRequest = contributeToGoalRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ContributeToGoalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/goals/{id}/contributions
     * Record a contribution to a savings goal
     * Logs a contribution event against a goal from a specific account. Required: &#x60;accountId&#x60; and &#x60;amount&#x60; (in dollars, positive for a contribution, negative for a withdrawal). &#x60;date&#x60; defaults to today if omitted.  Use after a manual transfer the user wants attributed to the goal, or to backfill historical progress. Updates the goal&#39;s &#x60;currentAmount&#x60; and appends to its event log (visible via &#x60;GET /v1/goals/{id}/events&#x60;).  Distinct from &#x60;PUT /v1/goals/{id}/budget&#x60; which sets the planned monthly contribution (forecast) rather than logging an actual one. 
     * @param id Monarch savings-goal id.
     * @param contributeToGoalRequest 
     * @return ApiResponse<ContributeToGoalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun contributeToGoalWithHttpInfo(id: kotlin.String, contributeToGoalRequest: ContributeToGoalRequest) : ApiResponse<ContributeToGoalResponse?> {
        val localVariableConfig = contributeToGoalRequestConfig(id = id, contributeToGoalRequest = contributeToGoalRequest)

        return request<ContributeToGoalRequest, ContributeToGoalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation contributeToGoal
     *
     * @param id Monarch savings-goal id.
     * @param contributeToGoalRequest 
     * @return RequestConfig
     */
    fun contributeToGoalRequestConfig(id: kotlin.String, contributeToGoalRequest: ContributeToGoalRequest) : RequestConfig<ContributeToGoalRequest> {
        val localVariableBody = contributeToGoalRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/goals/{id}/contributions".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/goals
     * Create a new savings or debt-payoff goal
     * Creates one savings goal. Wraps Monarch&#39;s &#x60;createSavingsGoals&#x60; batch mutation with a single-goal body for ergonomics.  Required: &#x60;name&#x60; and &#x60;targetAmount&#x60;. Optional: &#x60;targetDate&#x60;, &#x60;imageStorageProvider&#x60;/&#x60;imageStorageProviderId&#x60; for an icon, &#x60;accounts&#x60; to pre-link funding accounts. &#x60;type&#x60; defaults to &#x60;\&quot;savings\&quot;&#x60;; pass &#x60;\&quot;debt\&quot;&#x60; for a debt-payoff goal (sign convention flips: progress &#x3D; paying it DOWN).  Once created, set up monthly contributions via &#x60;PUT /v1/goals/{id}/budget&#x60; and log actuals via &#x60;POST /v1/goals/{id}/contributions&#x60;. 
     * @param createGoalRequest 
     * @return CreateGoalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createGoal(createGoalRequest: CreateGoalRequest) : CreateGoalResponse {
        val localVarResponse = createGoalWithHttpInfo(createGoalRequest = createGoalRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateGoalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/goals
     * Create a new savings or debt-payoff goal
     * Creates one savings goal. Wraps Monarch&#39;s &#x60;createSavingsGoals&#x60; batch mutation with a single-goal body for ergonomics.  Required: &#x60;name&#x60; and &#x60;targetAmount&#x60;. Optional: &#x60;targetDate&#x60;, &#x60;imageStorageProvider&#x60;/&#x60;imageStorageProviderId&#x60; for an icon, &#x60;accounts&#x60; to pre-link funding accounts. &#x60;type&#x60; defaults to &#x60;\&quot;savings\&quot;&#x60;; pass &#x60;\&quot;debt\&quot;&#x60; for a debt-payoff goal (sign convention flips: progress &#x3D; paying it DOWN).  Once created, set up monthly contributions via &#x60;PUT /v1/goals/{id}/budget&#x60; and log actuals via &#x60;POST /v1/goals/{id}/contributions&#x60;. 
     * @param createGoalRequest 
     * @return ApiResponse<CreateGoalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createGoalWithHttpInfo(createGoalRequest: CreateGoalRequest) : ApiResponse<CreateGoalResponse?> {
        val localVariableConfig = createGoalRequestConfig(createGoalRequest = createGoalRequest)

        return request<CreateGoalRequest, CreateGoalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createGoal
     *
     * @param createGoalRequest 
     * @return RequestConfig
     */
    fun createGoalRequestConfig(createGoalRequest: CreateGoalRequest) : RequestConfig<CreateGoalRequest> {
        val localVariableBody = createGoalRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/goals",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/goals/{id}/v2-delete
     * Delete a goal (v2 mutation)
     * Permanently delete a savings goal via the v2 &#x60;deleteGoalV2&#x60; mutation. Distinct from &#x60;DELETE /v1/goals/{id}/hard&#x60; (which uses the legacy &#x60;deleteSavingsGoal&#x60; path); the v2 path is preferred for goals created through the v2 flow.  Returns a flat &#x60;success&#x60; boolean and any payload errors. 
     * @param id Monarch savings-goal id.
     * @return MarkTransactionStreamAsNotRecurringResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteGoalV2(id: kotlin.String) : MarkTransactionStreamAsNotRecurringResponse {
        val localVarResponse = deleteGoalV2WithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MarkTransactionStreamAsNotRecurringResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/goals/{id}/v2-delete
     * Delete a goal (v2 mutation)
     * Permanently delete a savings goal via the v2 &#x60;deleteGoalV2&#x60; mutation. Distinct from &#x60;DELETE /v1/goals/{id}/hard&#x60; (which uses the legacy &#x60;deleteSavingsGoal&#x60; path); the v2 path is preferred for goals created through the v2 flow.  Returns a flat &#x60;success&#x60; boolean and any payload errors. 
     * @param id Monarch savings-goal id.
     * @return ApiResponse<MarkTransactionStreamAsNotRecurringResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteGoalV2WithHttpInfo(id: kotlin.String) : ApiResponse<MarkTransactionStreamAsNotRecurringResponse?> {
        val localVariableConfig = deleteGoalV2RequestConfig(id = id)

        return request<Unit, MarkTransactionStreamAsNotRecurringResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteGoalV2
     *
     * @param id Monarch savings-goal id.
     * @return RequestConfig
     */
    fun deleteGoalV2RequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/goals/{id}/v2-delete".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/goals/{id}
     * Get one savings goal
     * Returns the full detail for a single v2 savings goal: name, target amount, current balance, target date, type (savings or debt), priority, linked accounts, and archive state.  Use to surface a goal in a detail view or to inspect state before a PATCH or contribution. For the contribution / withdrawal event log use &#x60;GET /v1/goals/{id}/events&#x60;. 
     * @param id Monarch savings-goal id.
     * @return CreateGoalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getGoal(id: kotlin.String) : CreateGoalResponse {
        val localVarResponse = getGoalWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateGoalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/goals/{id}
     * Get one savings goal
     * Returns the full detail for a single v2 savings goal: name, target amount, current balance, target date, type (savings or debt), priority, linked accounts, and archive state.  Use to surface a goal in a detail view or to inspect state before a PATCH or contribution. For the contribution / withdrawal event log use &#x60;GET /v1/goals/{id}/events&#x60;. 
     * @param id Monarch savings-goal id.
     * @return ApiResponse<CreateGoalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getGoalWithHttpInfo(id: kotlin.String) : ApiResponse<CreateGoalResponse?> {
        val localVariableConfig = getGoalRequestConfig(id = id)

        return request<Unit, CreateGoalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getGoal
     *
     * @param id Monarch savings-goal id.
     * @return RequestConfig
     */
    fun getGoalRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/goals/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/goals/{id}/contribution-history
     * Goal contribution history
     * Ledger of contributions logged against one goal: date, amount, source account, optional notes. Distinct from &#x60;/v1/goals/{id}/events&#x60; which includes auto-linked transactions too; this endpoint returns only explicit contributions. 
     * @param id Monarch savings-goal id.
     * @return GetGoalContributionHistoryResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getGoalContributionHistory(id: kotlin.String) : GetGoalContributionHistoryResponse {
        val localVarResponse = getGoalContributionHistoryWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetGoalContributionHistoryResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/goals/{id}/contribution-history
     * Goal contribution history
     * Ledger of contributions logged against one goal: date, amount, source account, optional notes. Distinct from &#x60;/v1/goals/{id}/events&#x60; which includes auto-linked transactions too; this endpoint returns only explicit contributions. 
     * @param id Monarch savings-goal id.
     * @return ApiResponse<GetGoalContributionHistoryResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getGoalContributionHistoryWithHttpInfo(id: kotlin.String) : ApiResponse<GetGoalContributionHistoryResponse?> {
        val localVariableConfig = getGoalContributionHistoryRequestConfig(id = id)

        return request<Unit, GetGoalContributionHistoryResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getGoalContributionHistory
     *
     * @param id Monarch savings-goal id.
     * @return RequestConfig
     */
    fun getGoalContributionHistoryRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/goals/{id}/contribution-history".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/goals/{id}/projection
     * Goal projection chart
     * Forward projection of a goal&#39;s balance at the current planned contribution rate. Returns the projected completion date, months to target, and a per-month projected-balance series. 
     * @param id Monarch savings-goal id.
     * @return GetGoalProjectionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getGoalProjection(id: kotlin.String) : GetGoalProjectionResponse {
        val localVarResponse = getGoalProjectionWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetGoalProjectionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/goals/{id}/projection
     * Goal projection chart
     * Forward projection of a goal&#39;s balance at the current planned contribution rate. Returns the projected completion date, months to target, and a per-month projected-balance series. 
     * @param id Monarch savings-goal id.
     * @return ApiResponse<GetGoalProjectionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getGoalProjectionWithHttpInfo(id: kotlin.String) : ApiResponse<GetGoalProjectionResponse?> {
        val localVariableConfig = getGoalProjectionRequestConfig(id = id)

        return request<Unit, GetGoalProjectionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getGoalProjection
     *
     * @param id Monarch savings-goal id.
     * @return RequestConfig
     */
    fun getGoalProjectionRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/goals/{id}/projection".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/goals/totals/current-month
     * Current-month planned-contribution totals per goal
     * Returns the sum of &#x60;totalPlannedAmount&#x60; across the requested month window, broken out per goal. Used for \&quot;how much am I planning to contribute this month and to which goals\&quot; rollups without pulling each goal&#39;s full plan series.  Defaults to the current calendar month when both params are omitted (&#x60;startMonth &#x3D; first-of-this-month&#x60;, &#x60;endMonth &#x3D; first-of-this-month&#x60;). Pass a wider window to get a multi-month plan summary. 
     * @param startMonth First-of-month lower bound (&#x60;YYYY-MM-DD&#x60;). (optional)
     * @param endMonth First-of-month upper bound (&#x60;YYYY-MM-DD&#x60;). (optional)
     * @return GetGoalsCurrentMonthTotalsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getGoalsCurrentMonthTotals(startMonth: java.time.LocalDate? = null, endMonth: java.time.LocalDate? = null) : GetGoalsCurrentMonthTotalsResponse {
        val localVarResponse = getGoalsCurrentMonthTotalsWithHttpInfo(startMonth = startMonth, endMonth = endMonth)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetGoalsCurrentMonthTotalsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/goals/totals/current-month
     * Current-month planned-contribution totals per goal
     * Returns the sum of &#x60;totalPlannedAmount&#x60; across the requested month window, broken out per goal. Used for \&quot;how much am I planning to contribute this month and to which goals\&quot; rollups without pulling each goal&#39;s full plan series.  Defaults to the current calendar month when both params are omitted (&#x60;startMonth &#x3D; first-of-this-month&#x60;, &#x60;endMonth &#x3D; first-of-this-month&#x60;). Pass a wider window to get a multi-month plan summary. 
     * @param startMonth First-of-month lower bound (&#x60;YYYY-MM-DD&#x60;). (optional)
     * @param endMonth First-of-month upper bound (&#x60;YYYY-MM-DD&#x60;). (optional)
     * @return ApiResponse<GetGoalsCurrentMonthTotalsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getGoalsCurrentMonthTotalsWithHttpInfo(startMonth: java.time.LocalDate?, endMonth: java.time.LocalDate?) : ApiResponse<GetGoalsCurrentMonthTotalsResponse?> {
        val localVariableConfig = getGoalsCurrentMonthTotalsRequestConfig(startMonth = startMonth, endMonth = endMonth)

        return request<Unit, GetGoalsCurrentMonthTotalsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getGoalsCurrentMonthTotals
     *
     * @param startMonth First-of-month lower bound (&#x60;YYYY-MM-DD&#x60;). (optional)
     * @param endMonth First-of-month upper bound (&#x60;YYYY-MM-DD&#x60;). (optional)
     * @return RequestConfig
     */
    fun getGoalsCurrentMonthTotalsRequestConfig(startMonth: java.time.LocalDate?, endMonth: java.time.LocalDate?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (startMonth != null) {
                    put("startMonth", listOf(parseDateToQueryString(startMonth)))
                }
                if (endMonth != null) {
                    put("endMonth", listOf(parseDateToQueryString(endMonth)))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/goals/totals/current-month",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/goals/{id}/hard
     * Hard-delete a savings goal
     * Permanently removes the goal. **No undo**. Distinct from &#x60;DELETE /v1/goals/{id}&#x60; (which archives / soft-deletes and is reversible via the unarchive endpoint).  After this call the goal disappears from &#x60;GET /v1/goals&#x60; entirely and its event log is no longer queryable. Use only when the user explicitly wants to purge a goal, not for routine cleanup. 
     * @param id Monarch savings-goal id.
     * @return HardDeleteGoalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun hardDeleteGoal(id: kotlin.String) : HardDeleteGoalResponse {
        val localVarResponse = hardDeleteGoalWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HardDeleteGoalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/goals/{id}/hard
     * Hard-delete a savings goal
     * Permanently removes the goal. **No undo**. Distinct from &#x60;DELETE /v1/goals/{id}&#x60; (which archives / soft-deletes and is reversible via the unarchive endpoint).  After this call the goal disappears from &#x60;GET /v1/goals&#x60; entirely and its event log is no longer queryable. Use only when the user explicitly wants to purge a goal, not for routine cleanup. 
     * @param id Monarch savings-goal id.
     * @return ApiResponse<HardDeleteGoalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun hardDeleteGoalWithHttpInfo(id: kotlin.String) : ApiResponse<HardDeleteGoalResponse?> {
        val localVariableConfig = hardDeleteGoalRequestConfig(id = id)

        return request<Unit, HardDeleteGoalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation hardDeleteGoal
     *
     * @param id Monarch savings-goal id.
     * @return RequestConfig
     */
    fun hardDeleteGoalRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/goals/{id}/hard".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/transactions/{id}/goal-link
     * Link a transaction to a savings goal
     * Create a goal-event that ties a single transaction to a goal. The transaction&#39;s &#x60;savingsGoalEvent&#x60; becomes non-null and the goal balance reconciliation picks it up. Used to credit a specific purchase (\&quot;plane tickets\&quot;) against the matching goal (\&quot;Vacation\&quot;).  Pair with &#x60;DELETE /v1/transactions/{id}/goal-link&#x60; to unlink. 
     * @param id Monarch transaction id.
     * @param linkTransactionToGoalRequest 
     * @return LinkTransactionToGoalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun linkTransactionToGoal(id: kotlin.String, linkTransactionToGoalRequest: LinkTransactionToGoalRequest) : LinkTransactionToGoalResponse {
        val localVarResponse = linkTransactionToGoalWithHttpInfo(id = id, linkTransactionToGoalRequest = linkTransactionToGoalRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LinkTransactionToGoalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/transactions/{id}/goal-link
     * Link a transaction to a savings goal
     * Create a goal-event that ties a single transaction to a goal. The transaction&#39;s &#x60;savingsGoalEvent&#x60; becomes non-null and the goal balance reconciliation picks it up. Used to credit a specific purchase (\&quot;plane tickets\&quot;) against the matching goal (\&quot;Vacation\&quot;).  Pair with &#x60;DELETE /v1/transactions/{id}/goal-link&#x60; to unlink. 
     * @param id Monarch transaction id.
     * @param linkTransactionToGoalRequest 
     * @return ApiResponse<LinkTransactionToGoalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun linkTransactionToGoalWithHttpInfo(id: kotlin.String, linkTransactionToGoalRequest: LinkTransactionToGoalRequest) : ApiResponse<LinkTransactionToGoalResponse?> {
        val localVariableConfig = linkTransactionToGoalRequestConfig(id = id, linkTransactionToGoalRequest = linkTransactionToGoalRequest)

        return request<LinkTransactionToGoalRequest, LinkTransactionToGoalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation linkTransactionToGoal
     *
     * @param id Monarch transaction id.
     * @param linkTransactionToGoalRequest 
     * @return RequestConfig
     */
    fun linkTransactionToGoalRequestConfig(id: kotlin.String, linkTransactionToGoalRequest: LinkTransactionToGoalRequest) : RequestConfig<LinkTransactionToGoalRequest> {
        val localVariableBody = linkTransactionToGoalRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/transactions/{id}/goal-link".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/goals/{id}/events
     * Event log for one savings goal
     * Returns the full event ledger for a single goal: every contribution, withdrawal, and transaction Monarch auto-linked to the goal. Each event has type, amount, date, account, and source transaction id (if any).  Use to surface a \&quot;history\&quot; tab on a goal detail view or to compute actual-vs-planned contribution totals over time. For a quick current-month rollup across all goals use &#x60;GET /v1/goals/current-month-totals&#x60;. 
     * @param id Monarch savings-goal id.
     * @return ListGoalEventsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listGoalEvents(id: kotlin.String) : ListGoalEventsResponse {
        val localVarResponse = listGoalEventsWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ListGoalEventsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/goals/{id}/events
     * Event log for one savings goal
     * Returns the full event ledger for a single goal: every contribution, withdrawal, and transaction Monarch auto-linked to the goal. Each event has type, amount, date, account, and source transaction id (if any).  Use to surface a \&quot;history\&quot; tab on a goal detail view or to compute actual-vs-planned contribution totals over time. For a quick current-month rollup across all goals use &#x60;GET /v1/goals/current-month-totals&#x60;. 
     * @param id Monarch savings-goal id.
     * @return ApiResponse<ListGoalEventsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listGoalEventsWithHttpInfo(id: kotlin.String) : ApiResponse<ListGoalEventsResponse?> {
        val localVariableConfig = listGoalEventsRequestConfig(id = id)

        return request<Unit, ListGoalEventsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listGoalEvents
     *
     * @param id Monarch savings-goal id.
     * @return RequestConfig
     */
    fun listGoalEventsRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/goals/{id}/events".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/goals
     * List all savings goals
     * Returns every v2 savings goal: active, archived, hard-deleted-but- soft-still-visible, debt and savings types together. Each entry carries name, target amount, current progress, priority, linked accounts, and &#x60;archivedAt&#x60;.  Filter client-side on &#x60;archivedAt &#x3D;&#x3D; null&#x60; to hide archived. Sort on &#x60;priority&#x60; for the user&#39;s intended display order. For one goal&#39;s detail use &#x60;GET /v1/goals/{id}&#x60;; for the event log use &#x60;GET /v1/goals/{id}/events&#x60;. 
     * @return ListGoalsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listGoals() : ListGoalsResponse {
        val localVarResponse = listGoalsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ListGoalsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/goals
     * List all savings goals
     * Returns every v2 savings goal: active, archived, hard-deleted-but- soft-still-visible, debt and savings types together. Each entry carries name, target amount, current progress, priority, linked accounts, and &#x60;archivedAt&#x60;.  Filter client-side on &#x60;archivedAt &#x3D;&#x3D; null&#x60; to hide archived. Sort on &#x60;priority&#x60; for the user&#39;s intended display order. For one goal&#39;s detail use &#x60;GET /v1/goals/{id}&#x60;; for the event log use &#x60;GET /v1/goals/{id}/events&#x60;. 
     * @return ApiResponse<ListGoalsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listGoalsWithHttpInfo() : ApiResponse<ListGoalsResponse?> {
        val localVariableConfig = listGoalsRequestConfig()

        return request<Unit, ListGoalsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listGoals
     *
     * @return RequestConfig
     */
    fun listGoalsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/goals",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/goals/{id}/complete
     * Mark a goal complete
     * Stamp a savings goal &#x60;completedAt&#x3D;now&#x60;. Surfaces a celebration in the UI and freezes the goal balance display. Idempotent - replays do not re-trigger the celebration.  Pair with &#x60;POST /v1/goals/{id}/incomplete&#x60; to un-mark a goal that was marked complete by mistake. 
     * @param id Monarch savings-goal id.
     * @return MarkGoalCompleteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun markGoalComplete(id: kotlin.String) : MarkGoalCompleteResponse {
        val localVarResponse = markGoalCompleteWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MarkGoalCompleteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/goals/{id}/complete
     * Mark a goal complete
     * Stamp a savings goal &#x60;completedAt&#x3D;now&#x60;. Surfaces a celebration in the UI and freezes the goal balance display. Idempotent - replays do not re-trigger the celebration.  Pair with &#x60;POST /v1/goals/{id}/incomplete&#x60; to un-mark a goal that was marked complete by mistake. 
     * @param id Monarch savings-goal id.
     * @return ApiResponse<MarkGoalCompleteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun markGoalCompleteWithHttpInfo(id: kotlin.String) : ApiResponse<MarkGoalCompleteResponse?> {
        val localVariableConfig = markGoalCompleteRequestConfig(id = id)

        return request<Unit, MarkGoalCompleteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation markGoalComplete
     *
     * @param id Monarch savings-goal id.
     * @return RequestConfig
     */
    fun markGoalCompleteRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/goals/{id}/complete".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/goals/{id}/incomplete
     * Mark a goal incomplete
     * Clear a savings goal&#39;s &#x60;completedAt&#x60;, reverting it back to \&quot;in progress\&quot;. Used to undo a &#x60;POST /v1/goals/{id}/complete&#x60; performed in error. 
     * @param id Monarch savings-goal id.
     * @return MarkGoalCompleteResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun markGoalIncomplete(id: kotlin.String) : MarkGoalCompleteResponse {
        val localVarResponse = markGoalIncompleteWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MarkGoalCompleteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/goals/{id}/incomplete
     * Mark a goal incomplete
     * Clear a savings goal&#39;s &#x60;completedAt&#x60;, reverting it back to \&quot;in progress\&quot;. Used to undo a &#x60;POST /v1/goals/{id}/complete&#x60; performed in error. 
     * @param id Monarch savings-goal id.
     * @return ApiResponse<MarkGoalCompleteResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun markGoalIncompleteWithHttpInfo(id: kotlin.String) : ApiResponse<MarkGoalCompleteResponse?> {
        val localVariableConfig = markGoalIncompleteRequestConfig(id = id)

        return request<Unit, MarkGoalCompleteResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation markGoalIncomplete
     *
     * @param id Monarch savings-goal id.
     * @return RequestConfig
     */
    fun markGoalIncompleteRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/goals/{id}/incomplete".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * PUT /v1/goals/{id}/budget
     * Set monthly budget allocation for a savings goal
     * Sets the planned contribution amount for a goal for one month, or (with &#x60;applyToFuture: true&#x60;) cascades the same amount to every subsequent month. This is the FORECAST, not a recorded contribution: use &#x60;POST /v1/goals/{id}/contributions&#x60; to log actual money in.  Required: &#x60;startDate&#x60; (first-of-month) and &#x60;amount&#x60;. &#x60;accountId&#x60; is optional: omit to set the household-level planned amount; supply when the contribution comes from one specific account.  Pairs with &#x60;GET /v1/goals/current-month-totals&#x60; to read back the planned totals. 
     * @param id Monarch savings-goal id.
     * @param setGoalBudgetAmountRequest 
     * @return MarkTransactionStreamAsNotRecurringResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun setGoalBudgetAmount(id: kotlin.String, setGoalBudgetAmountRequest: SetGoalBudgetAmountRequest) : MarkTransactionStreamAsNotRecurringResponse {
        val localVarResponse = setGoalBudgetAmountWithHttpInfo(id = id, setGoalBudgetAmountRequest = setGoalBudgetAmountRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MarkTransactionStreamAsNotRecurringResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /v1/goals/{id}/budget
     * Set monthly budget allocation for a savings goal
     * Sets the planned contribution amount for a goal for one month, or (with &#x60;applyToFuture: true&#x60;) cascades the same amount to every subsequent month. This is the FORECAST, not a recorded contribution: use &#x60;POST /v1/goals/{id}/contributions&#x60; to log actual money in.  Required: &#x60;startDate&#x60; (first-of-month) and &#x60;amount&#x60;. &#x60;accountId&#x60; is optional: omit to set the household-level planned amount; supply when the contribution comes from one specific account.  Pairs with &#x60;GET /v1/goals/current-month-totals&#x60; to read back the planned totals. 
     * @param id Monarch savings-goal id.
     * @param setGoalBudgetAmountRequest 
     * @return ApiResponse<MarkTransactionStreamAsNotRecurringResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun setGoalBudgetAmountWithHttpInfo(id: kotlin.String, setGoalBudgetAmountRequest: SetGoalBudgetAmountRequest) : ApiResponse<MarkTransactionStreamAsNotRecurringResponse?> {
        val localVariableConfig = setGoalBudgetAmountRequestConfig(id = id, setGoalBudgetAmountRequest = setGoalBudgetAmountRequest)

        return request<SetGoalBudgetAmountRequest, MarkTransactionStreamAsNotRecurringResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation setGoalBudgetAmount
     *
     * @param id Monarch savings-goal id.
     * @param setGoalBudgetAmountRequest 
     * @return RequestConfig
     */
    fun setGoalBudgetAmountRequestConfig(id: kotlin.String, setGoalBudgetAmountRequest: SetGoalBudgetAmountRequest) : RequestConfig<SetGoalBudgetAmountRequest> {
        val localVariableBody = setGoalBudgetAmountRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/v1/goals/{id}/budget".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/goals/{id}/spend
     * Spend from a savings goal
     * Record a spend event against a savings goal - i.e. \&quot;I used some of my &#x60;Vacation&#x60; goal balance to pay for the flight\&quot;. Pair with &#x60;POST /v1/goals/{id}/contributions&#x60; (contributions) and &#x60;POST /v1/goals/{id}/withdraw&#x60; (withdrawals back to source account).  Returns the created goal-event id. 
     * @param id Monarch savings-goal id.
     * @param spendFromGoalRequest 
     * @return SpendFromGoalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun spendFromGoal(id: kotlin.String, spendFromGoalRequest: SpendFromGoalRequest) : SpendFromGoalResponse {
        val localVarResponse = spendFromGoalWithHttpInfo(id = id, spendFromGoalRequest = spendFromGoalRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SpendFromGoalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/goals/{id}/spend
     * Spend from a savings goal
     * Record a spend event against a savings goal - i.e. \&quot;I used some of my &#x60;Vacation&#x60; goal balance to pay for the flight\&quot;. Pair with &#x60;POST /v1/goals/{id}/contributions&#x60; (contributions) and &#x60;POST /v1/goals/{id}/withdraw&#x60; (withdrawals back to source account).  Returns the created goal-event id. 
     * @param id Monarch savings-goal id.
     * @param spendFromGoalRequest 
     * @return ApiResponse<SpendFromGoalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun spendFromGoalWithHttpInfo(id: kotlin.String, spendFromGoalRequest: SpendFromGoalRequest) : ApiResponse<SpendFromGoalResponse?> {
        val localVariableConfig = spendFromGoalRequestConfig(id = id, spendFromGoalRequest = spendFromGoalRequest)

        return request<SpendFromGoalRequest, SpendFromGoalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation spendFromGoal
     *
     * @param id Monarch savings-goal id.
     * @param spendFromGoalRequest 
     * @return RequestConfig
     */
    fun spendFromGoalRequestConfig(id: kotlin.String, spendFromGoalRequest: SpendFromGoalRequest) : RequestConfig<SpendFromGoalRequest> {
        val localVariableBody = spendFromGoalRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/goals/{id}/spend".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/goals/{id}/unarchive
     * Un-archive a savings goal
     * Restores a previously archived goal back to active state. Inverse of &#x60;DELETE /v1/goals/{id}&#x60;: clears the upstream &#x60;archivedAt&#x60; timestamp and flips &#x60;status&#x60; back to &#x60;active&#x60;.  Use when a user accidentally archived a goal or wants to revive an old one. No-op if the goal is already active. For permanent removal use &#x60;DELETE /v1/goals/{id}/hard&#x60; (no undo). 
     * @param id Monarch savings-goal id.
     * @return CreateGoalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun unarchiveGoal(id: kotlin.String) : CreateGoalResponse {
        val localVarResponse = unarchiveGoalWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateGoalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/goals/{id}/unarchive
     * Un-archive a savings goal
     * Restores a previously archived goal back to active state. Inverse of &#x60;DELETE /v1/goals/{id}&#x60;: clears the upstream &#x60;archivedAt&#x60; timestamp and flips &#x60;status&#x60; back to &#x60;active&#x60;.  Use when a user accidentally archived a goal or wants to revive an old one. No-op if the goal is already active. For permanent removal use &#x60;DELETE /v1/goals/{id}/hard&#x60; (no undo). 
     * @param id Monarch savings-goal id.
     * @return ApiResponse<CreateGoalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun unarchiveGoalWithHttpInfo(id: kotlin.String) : ApiResponse<CreateGoalResponse?> {
        val localVariableConfig = unarchiveGoalRequestConfig(id = id)

        return request<Unit, CreateGoalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation unarchiveGoal
     *
     * @param id Monarch savings-goal id.
     * @return RequestConfig
     */
    fun unarchiveGoalRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/goals/{id}/unarchive".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/transactions/{id}/goal-link
     * Unlink any goal-reconciliation records for a transaction
     * Drops all goal-reconciliation records for one transaction (the inverse of &#x60;POST /v1/transactions/{id}/goal-link&#x60;). The transaction stops being credited against any goal. 
     * @param id Monarch transaction id.
     * @return MarkTransactionStreamAsNotRecurringResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun unlinkTransactionGoalRecords(id: kotlin.String) : MarkTransactionStreamAsNotRecurringResponse {
        val localVarResponse = unlinkTransactionGoalRecordsWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MarkTransactionStreamAsNotRecurringResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/transactions/{id}/goal-link
     * Unlink any goal-reconciliation records for a transaction
     * Drops all goal-reconciliation records for one transaction (the inverse of &#x60;POST /v1/transactions/{id}/goal-link&#x60;). The transaction stops being credited against any goal. 
     * @param id Monarch transaction id.
     * @return ApiResponse<MarkTransactionStreamAsNotRecurringResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun unlinkTransactionGoalRecordsWithHttpInfo(id: kotlin.String) : ApiResponse<MarkTransactionStreamAsNotRecurringResponse?> {
        val localVariableConfig = unlinkTransactionGoalRecordsRequestConfig(id = id)

        return request<Unit, MarkTransactionStreamAsNotRecurringResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation unlinkTransactionGoalRecords
     *
     * @param id Monarch transaction id.
     * @return RequestConfig
     */
    fun unlinkTransactionGoalRecordsRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/transactions/{id}/goal-link".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/goals/{id}
     * Update a savings goal
     * Patches one goal. Only populated fields are forwarded to Monarch; omit a field to leave it untouched.  Common edits: rename, change &#x60;targetAmount&#x60; or &#x60;targetDate&#x60;, re-link &#x60;accounts&#x60;, update the icon. To re-order priority across goals use &#x60;PUT /v1/goals/priorities&#x60; instead. To archive use &#x60;DELETE /v1/goals/{id}&#x60; (reversible) or &#x60;DELETE /v1/goals/{id}/hard&#x60; (permanent). 
     * @param id Monarch savings-goal id.
     * @param updateGoalRequest 
     * @return CreateGoalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateGoal(id: kotlin.String, updateGoalRequest: UpdateGoalRequest) : CreateGoalResponse {
        val localVarResponse = updateGoalWithHttpInfo(id = id, updateGoalRequest = updateGoalRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateGoalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/goals/{id}
     * Update a savings goal
     * Patches one goal. Only populated fields are forwarded to Monarch; omit a field to leave it untouched.  Common edits: rename, change &#x60;targetAmount&#x60; or &#x60;targetDate&#x60;, re-link &#x60;accounts&#x60;, update the icon. To re-order priority across goals use &#x60;PUT /v1/goals/priorities&#x60; instead. To archive use &#x60;DELETE /v1/goals/{id}&#x60; (reversible) or &#x60;DELETE /v1/goals/{id}/hard&#x60; (permanent). 
     * @param id Monarch savings-goal id.
     * @param updateGoalRequest 
     * @return ApiResponse<CreateGoalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateGoalWithHttpInfo(id: kotlin.String, updateGoalRequest: UpdateGoalRequest) : ApiResponse<CreateGoalResponse?> {
        val localVariableConfig = updateGoalRequestConfig(id = id, updateGoalRequest = updateGoalRequest)

        return request<UpdateGoalRequest, CreateGoalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateGoal
     *
     * @param id Monarch savings-goal id.
     * @param updateGoalRequest 
     * @return RequestConfig
     */
    fun updateGoalRequestConfig(id: kotlin.String, updateGoalRequest: UpdateGoalRequest) : RequestConfig<UpdateGoalRequest> {
        val localVariableBody = updateGoalRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/goals/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * PUT /v1/goals/priorities
     * Re-order savings goals by priority
     * Reorders goals by sending the full id list in the desired order. The proxy assigns &#x60;priority &#x3D; index&#x60; (0-based) to each id, then calls Monarch&#39;s batch priority mutation in one round-trip.  Send the COMPLETE goal id list, not a delta. Goals missing from the list keep their current priority but end up after all listed goals. Use after a drag-and-drop reorder in a goals UI. 
     * @param updateGoalsPrioritiesRequest 
     * @return UpdateGoalsPrioritiesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateGoalsPriorities(updateGoalsPrioritiesRequest: UpdateGoalsPrioritiesRequest) : UpdateGoalsPrioritiesResponse {
        val localVarResponse = updateGoalsPrioritiesWithHttpInfo(updateGoalsPrioritiesRequest = updateGoalsPrioritiesRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as UpdateGoalsPrioritiesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /v1/goals/priorities
     * Re-order savings goals by priority
     * Reorders goals by sending the full id list in the desired order. The proxy assigns &#x60;priority &#x3D; index&#x60; (0-based) to each id, then calls Monarch&#39;s batch priority mutation in one round-trip.  Send the COMPLETE goal id list, not a delta. Goals missing from the list keep their current priority but end up after all listed goals. Use after a drag-and-drop reorder in a goals UI. 
     * @param updateGoalsPrioritiesRequest 
     * @return ApiResponse<UpdateGoalsPrioritiesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateGoalsPrioritiesWithHttpInfo(updateGoalsPrioritiesRequest: UpdateGoalsPrioritiesRequest) : ApiResponse<UpdateGoalsPrioritiesResponse?> {
        val localVariableConfig = updateGoalsPrioritiesRequestConfig(updateGoalsPrioritiesRequest = updateGoalsPrioritiesRequest)

        return request<UpdateGoalsPrioritiesRequest, UpdateGoalsPrioritiesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateGoalsPriorities
     *
     * @param updateGoalsPrioritiesRequest 
     * @return RequestConfig
     */
    fun updateGoalsPrioritiesRequestConfig(updateGoalsPrioritiesRequest: UpdateGoalsPrioritiesRequest) : RequestConfig<UpdateGoalsPrioritiesRequest> {
        val localVariableBody = updateGoalsPrioritiesRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/v1/goals/priorities",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/goals/{id}/withdraw
     * Withdraw from a savings goal
     * Withdraw money from a savings goal back into a source account. Reverses (in spirit) a prior contribution; the goal balance drops by &#x60;amount&#x60;, and Monarch updates the account&#39;s available-for-goals balance.  Pair with &#x60;POST /v1/goals/{id}/contributions&#x60; to deposit. 
     * @param id Monarch savings-goal id.
     * @param withdrawFromGoalRequest 
     * @return WithdrawFromGoalResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun withdrawFromGoal(id: kotlin.String, withdrawFromGoalRequest: WithdrawFromGoalRequest) : WithdrawFromGoalResponse {
        val localVarResponse = withdrawFromGoalWithHttpInfo(id = id, withdrawFromGoalRequest = withdrawFromGoalRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as WithdrawFromGoalResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/goals/{id}/withdraw
     * Withdraw from a savings goal
     * Withdraw money from a savings goal back into a source account. Reverses (in spirit) a prior contribution; the goal balance drops by &#x60;amount&#x60;, and Monarch updates the account&#39;s available-for-goals balance.  Pair with &#x60;POST /v1/goals/{id}/contributions&#x60; to deposit. 
     * @param id Monarch savings-goal id.
     * @param withdrawFromGoalRequest 
     * @return ApiResponse<WithdrawFromGoalResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun withdrawFromGoalWithHttpInfo(id: kotlin.String, withdrawFromGoalRequest: WithdrawFromGoalRequest) : ApiResponse<WithdrawFromGoalResponse?> {
        val localVariableConfig = withdrawFromGoalRequestConfig(id = id, withdrawFromGoalRequest = withdrawFromGoalRequest)

        return request<WithdrawFromGoalRequest, WithdrawFromGoalResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation withdrawFromGoal
     *
     * @param id Monarch savings-goal id.
     * @param withdrawFromGoalRequest 
     * @return RequestConfig
     */
    fun withdrawFromGoalRequestConfig(id: kotlin.String, withdrawFromGoalRequest: WithdrawFromGoalRequest) : RequestConfig<WithdrawFromGoalRequest> {
        val localVariableBody = withdrawFromGoalRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/goals/{id}/withdraw".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
