/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.nicholasklaene.monarchbridge.client.models.DeleteMerchantResponse
import com.nicholasklaene.monarchbridge.client.models.GetMerchantResponse
import com.nicholasklaene.monarchbridge.client.models.GetMerchantStatsResponse
import com.nicholasklaene.monarchbridge.client.models.GetMerchantTransactionsResponse
import com.nicholasklaene.monarchbridge.client.models.RequestRefresh503Response
import com.nicholasklaene.monarchbridge.client.models.SearchMerchantsResponse
import com.nicholasklaene.monarchbridge.client.models.SetMerchantLogoRequest

import com.squareup.moshi.Json

import com.nicholasklaene.monarchbridge.client.infrastructure.ApiClient
import com.nicholasklaene.monarchbridge.client.infrastructure.ApiResponse
import com.nicholasklaene.monarchbridge.client.infrastructure.ClientException
import com.nicholasklaene.monarchbridge.client.infrastructure.ClientError
import com.nicholasklaene.monarchbridge.client.infrastructure.ServerException
import com.nicholasklaene.monarchbridge.client.infrastructure.ServerError
import com.nicholasklaene.monarchbridge.client.infrastructure.MultiValueMap
import com.nicholasklaene.monarchbridge.client.infrastructure.PartConfig
import com.nicholasklaene.monarchbridge.client.infrastructure.RequestConfig
import com.nicholasklaene.monarchbridge.client.infrastructure.RequestMethod
import com.nicholasklaene.monarchbridge.client.infrastructure.ResponseType
import com.nicholasklaene.monarchbridge.client.infrastructure.Success
import com.nicholasklaene.monarchbridge.client.infrastructure.toMultiValue

class MerchantsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:9084")
        }
    }

    /**
     * DELETE /v1/merchants/{id}
     * Delete a merchant
     * Removes a merchant from the catalog. **Destructive** for any transactions and rules that referenced this merchant unless you remap.  Pass &#x60;moveToId&#x60; to reassign every transaction and every auto-categorization rule that pointed at this merchant to a different merchant before deletion. Omit to orphan them (the transactions will fall back to displaying the raw &#x60;plaidName&#x60;).  Use &#x60;GET /v1/merchants/{id}&#x60; first to check &#x60;canBeDeleted&#x60; and &#x60;transactionCount&#x60;. 
     * @param id Monarch merchant id.
     * @param moveToId Reassign this merchant&#39;s transactions and rules to this merchant before deletion. (optional)
     * @return DeleteMerchantResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteMerchant(id: kotlin.String, moveToId: kotlin.String? = null) : DeleteMerchantResponse {
        val localVarResponse = deleteMerchantWithHttpInfo(id = id, moveToId = moveToId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DeleteMerchantResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/merchants/{id}
     * Delete a merchant
     * Removes a merchant from the catalog. **Destructive** for any transactions and rules that referenced this merchant unless you remap.  Pass &#x60;moveToId&#x60; to reassign every transaction and every auto-categorization rule that pointed at this merchant to a different merchant before deletion. Omit to orphan them (the transactions will fall back to displaying the raw &#x60;plaidName&#x60;).  Use &#x60;GET /v1/merchants/{id}&#x60; first to check &#x60;canBeDeleted&#x60; and &#x60;transactionCount&#x60;. 
     * @param id Monarch merchant id.
     * @param moveToId Reassign this merchant&#39;s transactions and rules to this merchant before deletion. (optional)
     * @return ApiResponse<DeleteMerchantResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteMerchantWithHttpInfo(id: kotlin.String, moveToId: kotlin.String?) : ApiResponse<DeleteMerchantResponse?> {
        val localVariableConfig = deleteMerchantRequestConfig(id = id, moveToId = moveToId)

        return request<Unit, DeleteMerchantResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteMerchant
     *
     * @param id Monarch merchant id.
     * @param moveToId Reassign this merchant&#39;s transactions and rules to this merchant before deletion. (optional)
     * @return RequestConfig
     */
    fun deleteMerchantRequestConfig(id: kotlin.String, moveToId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (moveToId != null) {
                    put("moveToId", listOf(moveToId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/merchants/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/merchants/{id}
     * Get full detail for one merchant
     * Returns the rich single-merchant view: id, name, &#x60;logoUrl&#x60;, &#x60;transactionCount&#x60;, &#x60;ruleCount&#x60;, &#x60;canBeDeleted&#x60;, &#x60;hasActiveRecurringStreams&#x60;, plus the merchant&#39;s recurring stream definition when present.  Wraps Monarch&#39;s &#x60;Common_GetEditMerchant&#x60; query, the richest single-merchant read in the bundle. Use before a delete to check &#x60;canBeDeleted&#x60;, before a rename to read the current name (required by &#x60;PATCH /v1/merchants/{id}/recurrence&#x60;), or in a detail view. 
     * @param id Monarch merchant id.
     * @return GetMerchantResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMerchant(id: kotlin.String) : GetMerchantResponse {
        val localVarResponse = getMerchantWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetMerchantResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/merchants/{id}
     * Get full detail for one merchant
     * Returns the rich single-merchant view: id, name, &#x60;logoUrl&#x60;, &#x60;transactionCount&#x60;, &#x60;ruleCount&#x60;, &#x60;canBeDeleted&#x60;, &#x60;hasActiveRecurringStreams&#x60;, plus the merchant&#39;s recurring stream definition when present.  Wraps Monarch&#39;s &#x60;Common_GetEditMerchant&#x60; query, the richest single-merchant read in the bundle. Use before a delete to check &#x60;canBeDeleted&#x60;, before a rename to read the current name (required by &#x60;PATCH /v1/merchants/{id}/recurrence&#x60;), or in a detail view. 
     * @param id Monarch merchant id.
     * @return ApiResponse<GetMerchantResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getMerchantWithHttpInfo(id: kotlin.String) : ApiResponse<GetMerchantResponse?> {
        val localVariableConfig = getMerchantRequestConfig(id = id)

        return request<Unit, GetMerchantResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMerchant
     *
     * @param id Monarch merchant id.
     * @return RequestConfig
     */
    fun getMerchantRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/merchants/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/merchants/{id}/stats
     * Per-merchant aggregate stats
     * Aggregate stats for one merchant across a window: total spend, transaction count, average ticket, first / last seen, and the count of distinct months with activity. Backs the merchant detail page&#39;s \&quot;Activity\&quot; card.  Use &#x60;GET /v1/merchants/{id}/transactions&#x60; for the row-level transactions list. 
     * @param id Monarch merchant id.
     * @param start Lower bound (inclusive), &#x60;YYYY-MM-DD&#x60;. (optional)
     * @param end Upper bound (inclusive), &#x60;YYYY-MM-DD&#x60;. (optional)
     * @return GetMerchantStatsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMerchantStats(id: kotlin.String, start: java.time.LocalDate? = null, end: java.time.LocalDate? = null) : GetMerchantStatsResponse {
        val localVarResponse = getMerchantStatsWithHttpInfo(id = id, start = start, end = end)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetMerchantStatsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/merchants/{id}/stats
     * Per-merchant aggregate stats
     * Aggregate stats for one merchant across a window: total spend, transaction count, average ticket, first / last seen, and the count of distinct months with activity. Backs the merchant detail page&#39;s \&quot;Activity\&quot; card.  Use &#x60;GET /v1/merchants/{id}/transactions&#x60; for the row-level transactions list. 
     * @param id Monarch merchant id.
     * @param start Lower bound (inclusive), &#x60;YYYY-MM-DD&#x60;. (optional)
     * @param end Upper bound (inclusive), &#x60;YYYY-MM-DD&#x60;. (optional)
     * @return ApiResponse<GetMerchantStatsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getMerchantStatsWithHttpInfo(id: kotlin.String, start: java.time.LocalDate?, end: java.time.LocalDate?) : ApiResponse<GetMerchantStatsResponse?> {
        val localVariableConfig = getMerchantStatsRequestConfig(id = id, start = start, end = end)

        return request<Unit, GetMerchantStatsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMerchantStats
     *
     * @param id Monarch merchant id.
     * @param start Lower bound (inclusive), &#x60;YYYY-MM-DD&#x60;. (optional)
     * @param end Upper bound (inclusive), &#x60;YYYY-MM-DD&#x60;. (optional)
     * @return RequestConfig
     */
    fun getMerchantStatsRequestConfig(id: kotlin.String, start: java.time.LocalDate?, end: java.time.LocalDate?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (start != null) {
                    put("start", listOf(parseDateToQueryString(start)))
                }
                if (end != null) {
                    put("end", listOf(parseDateToQueryString(end)))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/merchants/{id}/stats".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/merchants/{id}/transactions
     * Transactions for one merchant
     * Transaction list scoped to a single merchant. Lighter than calling &#x60;/v1/transactions?search&#x3D;&lt;merchant&gt;&#x60; when you already have the merchant id. Returns date, amount, merchant, and category per row. 
     * @param id Monarch merchant id.
     * @param limit Page size. (optional)
     * @param offset Page offset. (optional)
     * @return GetMerchantTransactionsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMerchantTransactions(id: kotlin.String, limit: kotlin.Int? = null, offset: kotlin.Int? = null) : GetMerchantTransactionsResponse {
        val localVarResponse = getMerchantTransactionsWithHttpInfo(id = id, limit = limit, offset = offset)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetMerchantTransactionsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/merchants/{id}/transactions
     * Transactions for one merchant
     * Transaction list scoped to a single merchant. Lighter than calling &#x60;/v1/transactions?search&#x3D;&lt;merchant&gt;&#x60; when you already have the merchant id. Returns date, amount, merchant, and category per row. 
     * @param id Monarch merchant id.
     * @param limit Page size. (optional)
     * @param offset Page offset. (optional)
     * @return ApiResponse<GetMerchantTransactionsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getMerchantTransactionsWithHttpInfo(id: kotlin.String, limit: kotlin.Int?, offset: kotlin.Int?) : ApiResponse<GetMerchantTransactionsResponse?> {
        val localVariableConfig = getMerchantTransactionsRequestConfig(id = id, limit = limit, offset = offset)

        return request<Unit, GetMerchantTransactionsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMerchantTransactions
     *
     * @param id Monarch merchant id.
     * @param limit Page size. (optional)
     * @param offset Page offset. (optional)
     * @return RequestConfig
     */
    fun getMerchantTransactionsRequestConfig(id: kotlin.String, limit: kotlin.Int?, offset: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/merchants/{id}/transactions".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/merchants/search
     * Search merchants by name
     * Free-text search across merchant names, ordered by transaction count (most-used first). Use to populate a merchant picker, resolve a merchant id by name, or browse the merchant catalog.  Two backing queries via the &#x60;withLogo&#x60; flag:  - &#x60;withLogo: false&#x60; (default): faster, omits &#x60;logoUrl&#x60;, but   supports the &#x60;includeIds&#x60; filter (repeat the query param to pin   specific merchants into the result set even if they don&#39;t match   the search text). - &#x60;withLogo: true&#x60;: includes &#x60;logoUrl&#x60; per merchant; supports   &#x60;offset&#x60; pagination but drops &#x60;includeIds&#x60;. 
     * @param q Free-text search across merchant names. (optional)
     * @param limit Max number of merchants to return. (optional)
     * @param offset Page offset. Only respected when &#x60;withLogo&#x60; is true. (optional)
     * @param withLogo When true, switch to the logo-enabled variant of the query. (optional, default to false)
     * @param includeIds Pin specific merchant ids into the result set. Repeat the query param for each id. Only respected when &#x60;withLogo&#x60; is false.  (optional)
     * @return SearchMerchantsResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun searchMerchants(q: kotlin.String? = null, limit: kotlin.Int? = null, offset: kotlin.Int? = null, withLogo: kotlin.Boolean? = false, includeIds: kotlin.collections.List<kotlin.String>? = null) : SearchMerchantsResponse {
        val localVarResponse = searchMerchantsWithHttpInfo(q = q, limit = limit, offset = offset, withLogo = withLogo, includeIds = includeIds)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SearchMerchantsResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/merchants/search
     * Search merchants by name
     * Free-text search across merchant names, ordered by transaction count (most-used first). Use to populate a merchant picker, resolve a merchant id by name, or browse the merchant catalog.  Two backing queries via the &#x60;withLogo&#x60; flag:  - &#x60;withLogo: false&#x60; (default): faster, omits &#x60;logoUrl&#x60;, but   supports the &#x60;includeIds&#x60; filter (repeat the query param to pin   specific merchants into the result set even if they don&#39;t match   the search text). - &#x60;withLogo: true&#x60;: includes &#x60;logoUrl&#x60; per merchant; supports   &#x60;offset&#x60; pagination but drops &#x60;includeIds&#x60;. 
     * @param q Free-text search across merchant names. (optional)
     * @param limit Max number of merchants to return. (optional)
     * @param offset Page offset. Only respected when &#x60;withLogo&#x60; is true. (optional)
     * @param withLogo When true, switch to the logo-enabled variant of the query. (optional, default to false)
     * @param includeIds Pin specific merchant ids into the result set. Repeat the query param for each id. Only respected when &#x60;withLogo&#x60; is false.  (optional)
     * @return ApiResponse<SearchMerchantsResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun searchMerchantsWithHttpInfo(q: kotlin.String?, limit: kotlin.Int?, offset: kotlin.Int?, withLogo: kotlin.Boolean?, includeIds: kotlin.collections.List<kotlin.String>?) : ApiResponse<SearchMerchantsResponse?> {
        val localVariableConfig = searchMerchantsRequestConfig(q = q, limit = limit, offset = offset, withLogo = withLogo, includeIds = includeIds)

        return request<Unit, SearchMerchantsResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation searchMerchants
     *
     * @param q Free-text search across merchant names. (optional)
     * @param limit Max number of merchants to return. (optional)
     * @param offset Page offset. Only respected when &#x60;withLogo&#x60; is true. (optional)
     * @param withLogo When true, switch to the logo-enabled variant of the query. (optional, default to false)
     * @param includeIds Pin specific merchant ids into the result set. Repeat the query param for each id. Only respected when &#x60;withLogo&#x60; is false.  (optional)
     * @return RequestConfig
     */
    fun searchMerchantsRequestConfig(q: kotlin.String?, limit: kotlin.Int?, offset: kotlin.Int?, withLogo: kotlin.Boolean?, includeIds: kotlin.collections.List<kotlin.String>?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (q != null) {
                    put("q", listOf(q.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
                if (withLogo != null) {
                    put("withLogo", listOf(withLogo.toString()))
                }
                if (includeIds != null) {
                    put("includeIds", toMultiValue(includeIds.toList(), "multi"))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/merchants/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/merchants/{id}/logo
     * Set a merchant&#39;s logo
     * Points the merchant at an existing Cloudinary asset by public id.  **Gotcha**: Monarch&#39;s &#x60;setMerchantLogo&#x60; mutation does NOT accept a binary upload. The asset must already exist on Cloudinary (typically uploaded via Monarch&#39;s web UI). Pass the asset&#39;s &#x60;cloudinaryPublicId&#x60;; send &#x60;null&#x60; or omit to clear the logo.  To upload a fresh logo you&#39;d need to upload to Cloudinary out-of-band first and then call this endpoint with the resulting public id (Monarch does not expose its Cloudinary signing for this use-case). 
     * @param id Monarch merchant id.
     * @param setMerchantLogoRequest 
     * @return GetMerchantResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun setMerchantLogo(id: kotlin.String, setMerchantLogoRequest: SetMerchantLogoRequest) : GetMerchantResponse {
        val localVarResponse = setMerchantLogoWithHttpInfo(id = id, setMerchantLogoRequest = setMerchantLogoRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetMerchantResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/merchants/{id}/logo
     * Set a merchant&#39;s logo
     * Points the merchant at an existing Cloudinary asset by public id.  **Gotcha**: Monarch&#39;s &#x60;setMerchantLogo&#x60; mutation does NOT accept a binary upload. The asset must already exist on Cloudinary (typically uploaded via Monarch&#39;s web UI). Pass the asset&#39;s &#x60;cloudinaryPublicId&#x60;; send &#x60;null&#x60; or omit to clear the logo.  To upload a fresh logo you&#39;d need to upload to Cloudinary out-of-band first and then call this endpoint with the resulting public id (Monarch does not expose its Cloudinary signing for this use-case). 
     * @param id Monarch merchant id.
     * @param setMerchantLogoRequest 
     * @return ApiResponse<GetMerchantResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun setMerchantLogoWithHttpInfo(id: kotlin.String, setMerchantLogoRequest: SetMerchantLogoRequest) : ApiResponse<GetMerchantResponse?> {
        val localVariableConfig = setMerchantLogoRequestConfig(id = id, setMerchantLogoRequest = setMerchantLogoRequest)

        return request<SetMerchantLogoRequest, GetMerchantResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation setMerchantLogo
     *
     * @param id Monarch merchant id.
     * @param setMerchantLogoRequest 
     * @return RequestConfig
     */
    fun setMerchantLogoRequestConfig(id: kotlin.String, setMerchantLogoRequest: SetMerchantLogoRequest) : RequestConfig<SetMerchantLogoRequest> {
        val localVariableBody = setMerchantLogoRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/merchants/{id}/logo".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
