/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param month 
 * @param totalBudget 
 * @param totalActual 
 * @param varianceAmount 
 * @param variancePercent 
 */


data class BudgetTimelineMonth (

    @Json(name = "month")
    val month: kotlin.String? = null,

    @Json(name = "totalBudget")
    val totalBudget: kotlin.Double? = null,

    @Json(name = "totalActual")
    val totalActual: kotlin.Double? = null,

    @Json(name = "varianceAmount")
    val varianceAmount: kotlin.Double? = null,

    @Json(name = "variancePercent")
    val variancePercent: kotlin.Double? = null

) {


}

