/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.BulkMutationError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param success 
 * @param affectedCount Number of rows Monarch actually updated.
 * @param errors 
 */


data class BulkUpdateTransactionsResponseData (

    @Json(name = "success")
    val success: kotlin.Boolean,

    /* Number of rows Monarch actually updated. */
    @Json(name = "affectedCount")
    val affectedCount: kotlin.Int,

    @Json(name = "errors")
    val errors: kotlin.collections.List<BulkMutationError>? = null

) {


}

