/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.CashflowCategoryGroupRef

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param categoryGroup 
 * @param sum 
 */


data class CashflowCategoryGroupRow (

    @Json(name = "categoryGroup")
    val categoryGroup: CashflowCategoryGroupRef,

    @Json(name = "sum")
    val sum: kotlin.Double? = null

) {


}

