/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.TransactionRuleAmountCriterion
import com.nicholasklaene.monarchbridge.client.models.TransactionRuleSplitAction
import com.nicholasklaene.monarchbridge.client.models.TransactionRuleStringCriterion

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for creating / updating / previewing a rule. Every field is optional; only the fields you set drive the criteria and actions. Forwarded as-is to Monarch's `CreateTransactionRuleInput` / `UpdateTransactionRuleInput` / `TransactionRulePreviewInput`. The proxy injects path `{id}` into update calls; for create / preview the body alone is sufficient. 
 *
 * @param merchantCriteriaUseOriginalStatement 
 * @param merchantCriteria 
 * @param originalStatementCriteria 
 * @param merchantNameCriteria 
 * @param amountCriteria 
 * @param categoryIds 
 * @param accountIds 
 * @param criteriaOwnerIsJoint 
 * @param criteriaOwnerUserIds 
 * @param criteriaBusinessEntityIds 
 * @param criteriaBusinessEntityIsUnassigned 
 * @param setMerchantAction Merchant id to set on match.
 * @param setCategoryAction Category id to set on match.
 * @param addTagsAction Tag ids to add on match (additive; does not replace existing tags).
 * @param linkGoalAction 
 * @param linkSavingsGoalAction 
 * @param needsReviewByUserAction User id to assign for review.
 * @param unassignNeedsReviewByUserAction 
 * @param sendNotificationAction 
 * @param setHideFromReportsAction 
 * @param setLinkToPaydownBudgetAction 
 * @param reviewStatusAction 
 * @param actionSetOwnerIsJoint 
 * @param actionSetOwner User id to set as transaction owner on match.
 * @param actionSetBusinessEntity Business entity id to assign on match.
 * @param actionSetBusinessEntityIsUnassigned 
 * @param splitTransactionsAction 
 */


data class CreateTransactionRuleRequest (

    @Json(name = "merchantCriteriaUseOriginalStatement")
    val merchantCriteriaUseOriginalStatement: kotlin.Boolean? = null,

    @Json(name = "merchantCriteria")
    val merchantCriteria: kotlin.collections.List<TransactionRuleStringCriterion>? = null,

    @Json(name = "originalStatementCriteria")
    val originalStatementCriteria: kotlin.collections.List<TransactionRuleStringCriterion>? = null,

    @Json(name = "merchantNameCriteria")
    val merchantNameCriteria: kotlin.collections.List<TransactionRuleStringCriterion>? = null,

    @Json(name = "amountCriteria")
    val amountCriteria: TransactionRuleAmountCriterion? = null,

    @Json(name = "categoryIds")
    val categoryIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "accountIds")
    val accountIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "criteriaOwnerIsJoint")
    val criteriaOwnerIsJoint: kotlin.Boolean? = null,

    @Json(name = "criteriaOwnerUserIds")
    val criteriaOwnerUserIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "criteriaBusinessEntityIds")
    val criteriaBusinessEntityIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "criteriaBusinessEntityIsUnassigned")
    val criteriaBusinessEntityIsUnassigned: kotlin.Boolean? = null,

    /* Merchant id to set on match. */
    @Json(name = "setMerchantAction")
    val setMerchantAction: kotlin.String? = null,

    /* Category id to set on match. */
    @Json(name = "setCategoryAction")
    val setCategoryAction: kotlin.String? = null,

    /* Tag ids to add on match (additive; does not replace existing tags). */
    @Json(name = "addTagsAction")
    val addTagsAction: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "linkGoalAction")
    val linkGoalAction: kotlin.String? = null,

    @Json(name = "linkSavingsGoalAction")
    val linkSavingsGoalAction: kotlin.String? = null,

    /* User id to assign for review. */
    @Json(name = "needsReviewByUserAction")
    val needsReviewByUserAction: kotlin.String? = null,

    @Json(name = "unassignNeedsReviewByUserAction")
    val unassignNeedsReviewByUserAction: kotlin.Boolean? = null,

    @Json(name = "sendNotificationAction")
    val sendNotificationAction: kotlin.Boolean? = null,

    @Json(name = "setHideFromReportsAction")
    val setHideFromReportsAction: kotlin.Boolean? = null,

    @Json(name = "setLinkToPaydownBudgetAction")
    val setLinkToPaydownBudgetAction: kotlin.Boolean? = null,

    @Json(name = "reviewStatusAction")
    val reviewStatusAction: kotlin.String? = null,

    @Json(name = "actionSetOwnerIsJoint")
    val actionSetOwnerIsJoint: kotlin.Boolean? = null,

    /* User id to set as transaction owner on match. */
    @Json(name = "actionSetOwner")
    val actionSetOwner: kotlin.String? = null,

    /* Business entity id to assign on match. */
    @Json(name = "actionSetBusinessEntity")
    val actionSetBusinessEntity: kotlin.String? = null,

    @Json(name = "actionSetBusinessEntityIsUnassigned")
    val actionSetBusinessEntityIsUnassigned: kotlin.Boolean? = null,

    @Json(name = "splitTransactionsAction")
    val splitTransactionsAction: TransactionRuleSplitAction? = null

) {


}

