/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.PaycheckEmployer

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param employer 
 */


data class CreatePaycheckEmployerResponseData (

    @Json(name = "employer")
    val employer: PaycheckEmployer

) {


}

