/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deleted True when Monarch confirms the credential was deleted.
 */


data class DeleteInstitutionResponseData (

    /* True when Monarch confirms the credential was deleted. */
    @Json(name = "deleted")
    val deleted: kotlin.Boolean

) {


}

