/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Envelope for every `/v1/{advice,forecast,bills,equity-grants,report-configs, business-entities}/_*` feature-area endpoint. `data` is the raw Monarch GraphQL response tree as a FreeForm map; the proxy does not type the deep shape because these Monarch surfaces (advice items, forecast scenarios, bills, equity grants, report configs, business entities) churn per release and are wiring-only here. 
 *
 * @param `data` Free-form pass-through from upstream Monarch. Shape is documented per-endpoint; treat as a typed `Map<String, Any?>`. Use this for portions of the response we intentionally leave untyped because the upstream tree is too deep/volatile to model. 
 */


data class FeatureAreaResponse (

    /* Free-form pass-through from upstream Monarch. Shape is documented per-endpoint; treat as a typed `Map<String, Any?>`. Use this for portions of the response we intentionally leave untyped because the upstream tree is too deep/volatile to model.  */
    @Json(name = "data")
    val `data`: kotlin.collections.Map<kotlin.String, kotlin.Any>

) {


}

