/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Most-recent generation run metadata.
 *
 * @param id 
 * @param status 
 * @param createdAt 
 * @param insightsGeneratedCount 
 */


data class FinancialInsightRun (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,

    @Json(name = "insightsGeneratedCount")
    val insightsGeneratedCount: kotlin.Int? = null

) {


}

