/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param includeInNetWorth 
 * @param displayBalance 
 * @param accountType 
 */


data class GetAccountBalanceAtDateResponseData (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "includeInNetWorth")
    val includeInNetWorth: kotlin.Boolean,

    @Json(name = "displayBalance")
    val displayBalance: kotlin.Double? = null,

    @Json(name = "accountType")
    val accountType: kotlin.String? = null

) {


}

