/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.CashflowCategoryGroupRow
import com.nicholasklaene.monarchbridge.client.models.CashflowEntityCategoryRow
import com.nicholasklaene.monarchbridge.client.models.CashflowMerchantRow
import com.nicholasklaene.monarchbridge.client.models.CashflowSummary
import com.nicholasklaene.monarchbridge.client.models.CashflowTimeframeBucket

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param summary 
 * @param byYear 
 * @param byMonth 
 * @param byQuarter 
 * @param byCategory 
 * @param byCategoryGroup 
 * @param byMerchant 
 */


data class GetCashflowFilteredResponseData (

    @Json(name = "summary")
    val summary: CashflowSummary? = null,

    @Json(name = "byYear")
    val byYear: kotlin.collections.List<CashflowTimeframeBucket>? = null,

    @Json(name = "byMonth")
    val byMonth: kotlin.collections.List<CashflowTimeframeBucket>? = null,

    @Json(name = "byQuarter")
    val byQuarter: kotlin.collections.List<CashflowTimeframeBucket>? = null,

    @Json(name = "byCategory")
    val byCategory: kotlin.collections.List<CashflowEntityCategoryRow>? = null,

    @Json(name = "byCategoryGroup")
    val byCategoryGroup: kotlin.collections.List<CashflowCategoryGroupRow>? = null,

    @Json(name = "byMerchant")
    val byMerchant: kotlin.collections.List<CashflowMerchantRow>? = null

) {


}

