/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param entitlements 
 */


data class GetEntitlementsResponseData (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "entitlements")
    val entitlements: kotlin.collections.List<kotlin.String>

) {


}

