/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.GetNotificationsResponseDataEdgesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param edges 
 * @param hasNextPage 
 * @param endCursor 
 */


data class GetNotificationsResponseData (

    @Json(name = "edges")
    val edges: kotlin.collections.List<GetNotificationsResponseDataEdgesInner>,

    @Json(name = "hasNextPage")
    val hasNextPage: kotlin.Boolean? = null,

    @Json(name = "endCursor")
    val endCursor: kotlin.String? = null

) {


}

