/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.DuplicateGroupKey
import com.nicholasklaene.monarchbridge.client.models.Transaction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param key 
 * @param transactions 
 */


data class GetTransactionsDuplicatesResponseDataGroupsInner (

    @Json(name = "key")
    val key: DuplicateGroupKey,

    @Json(name = "transactions")
    val transactions: kotlin.collections.List<Transaction>

) {


}

