/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.TransactionAuditEntry

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertyEntries 
 */


data class GetTransactionAuditLogResponseData (

    @Json(name = "entries")
    val propertyEntries: kotlin.collections.List<TransactionAuditEntry>

) {


}

