/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param zpid 
 * @param addressStreet 
 * @param addressCity 
 * @param addressStateAbbr 
 * @param addressPostalCode 
 * @param zestimate 
 */


data class GetZestimateResponseDataZestimatesInner (

    @Json(name = "zpid")
    val zpid: kotlin.String? = null,

    @Json(name = "addressStreet")
    val addressStreet: kotlin.String? = null,

    @Json(name = "addressCity")
    val addressCity: kotlin.String? = null,

    @Json(name = "addressStateAbbr")
    val addressStateAbbr: kotlin.String? = null,

    @Json(name = "addressPostalCode")
    val addressPostalCode: kotlin.String? = null,

    @Json(name = "zestimate")
    val zestimate: kotlin.Double? = null

) {


}

