/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param goalEventId 
 * @param transactionId 
 * @param goalId 
 */


data class LinkTransactionToGoalResponseData (

    @Json(name = "goalEventId")
    val goalEventId: kotlin.String,

    @Json(name = "transactionId")
    val transactionId: kotlin.String? = null,

    @Json(name = "goalId")
    val goalId: kotlin.String? = null

) {


}

