/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param month 
 * @param netIncome 
 * @param totalSpending 
 * @param totalIncome 
 * @param savingsRate 
 * @param topMerchant 
 * @param topCategory 
 * @param biggestSpend 
 */


data class MonthlyReportSummary (

    @Json(name = "month")
    val month: kotlin.String? = null,

    @Json(name = "netIncome")
    val netIncome: kotlin.Double? = null,

    @Json(name = "totalSpending")
    val totalSpending: kotlin.Double? = null,

    @Json(name = "totalIncome")
    val totalIncome: kotlin.Double? = null,

    @Json(name = "savingsRate")
    val savingsRate: kotlin.Double? = null,

    @Json(name = "topMerchant")
    val topMerchant: kotlin.String? = null,

    @Json(name = "topCategory")
    val topCategory: kotlin.String? = null,

    @Json(name = "biggestSpend")
    val biggestSpend: kotlin.Double? = null

) {


}

