/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One line-item deduction from a paycheck (pre-tax, tax, post-tax).
 *
 * @param id 
 * @param deductionType Monarch enum of payroll deduction categories (e.g. `federal_income_tax`, `traditional_401k`, `medical_insurance`, `custom`). When `custom`, see `customDeductionName`. 
 * @param amount Dollar amount of the deduction (always positive).
 * @param customDeductionName Free-text label when `deductionType=custom`; null otherwise.
 * @param createdAt 
 */


data class PaycheckDeduction (

    @Json(name = "id")
    val id: kotlin.String,

    /* Monarch enum of payroll deduction categories (e.g. `federal_income_tax`, `traditional_401k`, `medical_insurance`, `custom`). When `custom`, see `customDeductionName`.  */
    @Json(name = "deductionType")
    val deductionType: kotlin.String,

    /* Dollar amount of the deduction (always positive). */
    @Json(name = "amount")
    val amount: kotlin.Double,

    /* Free-text label when `deductionType=custom`; null otherwise. */
    @Json(name = "customDeductionName")
    val customDeductionName: kotlin.String? = null,

    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null

) {


}

