/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param securityName 
 * @param holdingIds 
 * @param ticker 
 * @param securityType 
 * @param securityTypeDisplay 
 * @param quantity 
 * @param `value` 
 */


data class PortfolioAllocationHolding (

    @Json(name = "securityName")
    val securityName: kotlin.String,

    @Json(name = "holdingIds")
    val holdingIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "ticker")
    val ticker: kotlin.String? = null,

    @Json(name = "securityType")
    val securityType: kotlin.String? = null,

    @Json(name = "securityTypeDisplay")
    val securityTypeDisplay: kotlin.String? = null,

    @Json(name = "quantity")
    val quantity: kotlin.Double? = null,

    @Json(name = "value")
    val `value`: kotlin.Double? = null

) {


}

