/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param displayBalancePreview 
 */


data class PreviewAccountBalanceResponseData (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "displayBalancePreview")
    val displayBalancePreview: kotlin.Double? = null

) {


}

