/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param date 
 * @param amount 
 * @param merchantName 
 * @param streamId 
 */


data class RecurringForecastEntry (

    @Json(name = "date")
    val date: java.time.LocalDate,

    @Json(name = "amount")
    val amount: kotlin.Double? = null,

    @Json(name = "merchantName")
    val merchantName: kotlin.String? = null,

    @Json(name = "streamId")
    val streamId: kotlin.String? = null

) {


}

