/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.SavingsRateMonth

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param monthlyRates 
 * @param overallSavingsRate 
 */


data class SavingsRateReport (

    @Json(name = "monthlyRates")
    val monthlyRates: kotlin.collections.List<SavingsRateMonth>,

    @Json(name = "overallSavingsRate")
    val overallSavingsRate: kotlin.Double? = null

) {


}

