/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param month 
 * @param savingsRate 
 * @param income 
 * @param expense 
 */


data class SavingsRateMonth (

    @Json(name = "month")
    val month: kotlin.String? = null,

    @Json(name = "savingsRate")
    val savingsRate: kotlin.Double? = null,

    @Json(name = "income")
    val income: kotlin.Double? = null,

    @Json(name = "expense")
    val expense: kotlin.Double? = null

) {


}

