/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `PATCH /v1/merchants/{id}/logo`. Wraps Monarch's `SetMerchantLogoInput`. Pass the existing Cloudinary asset's public id; this endpoint does NOT accept a binary upload. Send `cloudinaryPublicId: null` to clear the logo. 
 *
 * @param cloudinaryPublicId Cloudinary public id of an already-uploaded image asset. Null clears.
 */


data class SetMerchantLogoRequest (

    /* Cloudinary public id of an already-uploaded image asset. Null clears. */
    @Json(name = "cloudinaryPublicId")
    val cloudinaryPublicId: kotlin.String? = null

) {


}

