/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param transactionId 
 * @param tagIds 
 */


data class SetTransactionTagsResponseData (

    @Json(name = "transactionId")
    val transactionId: kotlin.String,

    @Json(name = "tagIds")
    val tagIds: kotlin.collections.List<kotlin.String>

) {


}

