/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.SpendingReportCategory

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param topCategories 
 * @param totalSpend 
 * @param totalBudget 
 * @param percentOfBudget 
 */


data class SpendingReport (

    @Json(name = "topCategories")
    val topCategories: kotlin.collections.List<SpendingReportCategory>,

    @Json(name = "totalSpend")
    val totalSpend: kotlin.Double? = null,

    @Json(name = "totalBudget")
    val totalBudget: kotlin.Double? = null,

    @Json(name = "percentOfBudget")
    val percentOfBudget: kotlin.Double? = null

) {


}

