/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sessionKey 
 * @param status 
 */


data class StartDownloadTransactionsResponseData (

    @Json(name = "sessionKey")
    val sessionKey: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String? = null

) {


}

