/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param classification 
 * @param targetPercent 
 * @param currentPercent 
 */


data class TargetAllocationEntry (

    @Json(name = "classification")
    val classification: kotlin.String,

    @Json(name = "targetPercent")
    val targetPercent: kotlin.Double? = null,

    @Json(name = "currentPercent")
    val currentPercent: kotlin.Double? = null

) {


}

