/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One manual cost-basis tax lot under a holding. `acquisitionQuantity` / `costBasisPerUnit` express the per-share cost basis at acquisition. 
 *
 * @param id 
 * @param createdAt 
 * @param acquisitionDate 
 * @param acquisitionQuantity 
 * @param costBasisPerUnit 
 */


data class TaxLot (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,

    @Json(name = "acquisitionDate")
    val acquisitionDate: java.time.LocalDate? = null,

    @Json(name = "acquisitionQuantity")
    val acquisitionQuantity: kotlin.Double? = null,

    @Json(name = "costBasisPerUnit")
    val costBasisPerUnit: kotlin.Double? = null

) {


}

