/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import com.nicholasklaene.monarchbridge.client.models.TaxCategoryRef
import com.nicholasklaene.monarchbridge.client.models.TaxLineItemInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param lineItem 
 * @param schedule 
 * @param taxYear 
 * @param category 
 * @param lineItemInfo 
 */


data class TaxScheduleCategoryMapping (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "lineItem")
    val lineItem: kotlin.String? = null,

    @Json(name = "schedule")
    val schedule: kotlin.String? = null,

    @Json(name = "taxYear")
    val taxYear: kotlin.Int? = null,

    @Json(name = "category")
    val category: TaxCategoryRef? = null,

    @Json(name = "lineItemInfo")
    val lineItemInfo: TaxLineItemInfo? = null

) {


}

