/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sessionKey Use to poll `GET /v1/balance-history/{sessionKey}/status`.
 * @param status Current parse status (`pending`, `processing`, `completed`, `failed`).
 */


data class UploadAccountBalanceHistory202ResponseData (

    /* Use to poll `GET /v1/balance-history/{sessionKey}/status`. */
    @Json(name = "sessionKey")
    val sessionKey: kotlin.String,

    /* Current parse status (`pending`, `processing`, `completed`, `failed`). */
    @Json(name = "status")
    val status: kotlin.String

) {


}

