/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One module-specific card within a weekly recap (cashflow, biggest spend, etc.).
 *
 * @param module Card module identifier (e.g. `cashflow`, `top_categories`).
 * @param title 
 * @param headline 
 * @param message 
 * @param sentiment Monarch's tone tag (e.g. `positive`, `neutral`, `warning`).
 * @param titleMarkdown 
 * @param headlineMarkdown 
 * @param messageMarkdown 
 * @param metrics Free-form numeric metrics rendered inside the card.
 * @param richBlocks Free-form rich-text block tree.
 */


data class WeeklyRecapCard (

    /* Card module identifier (e.g. `cashflow`, `top_categories`). */
    @Json(name = "module")
    val module: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "headline")
    val headline: kotlin.String? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    /* Monarch's tone tag (e.g. `positive`, `neutral`, `warning`). */
    @Json(name = "sentiment")
    val sentiment: kotlin.String? = null,

    @Json(name = "titleMarkdown")
    val titleMarkdown: kotlin.String? = null,

    @Json(name = "headlineMarkdown")
    val headlineMarkdown: kotlin.String? = null,

    @Json(name = "messageMarkdown")
    val messageMarkdown: kotlin.String? = null,

    /* Free-form numeric metrics rendered inside the card. */
    @Json(name = "metrics")
    val metrics: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Free-form rich-text block tree. */
    @Json(name = "richBlocks")
    val richBlocks: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

