/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.BulkUpdateTransactionsRequest
import com.nicholasklaene.monarchbridge.client.models.BulkTransactionFilters
import com.nicholasklaene.monarchbridge.client.models.BulkTransactionUpdates

class BulkUpdateTransactionsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BulkUpdateTransactionsRequest
        //val modelInstance = BulkUpdateTransactionsRequest()

        // to test the property `expectedAffectedTransactionCount` - Safety check. Monarch refuses if actual affected count differs.
        should("test expectedAffectedTransactionCount") {
            // uncomment below to test the property
            //modelInstance.expectedAffectedTransactionCount shouldBe ("TODO")
        }

        // to test the property `updates`
        should("test updates") {
            // uncomment below to test the property
            //modelInstance.updates shouldBe ("TODO")
        }

        // to test the property `selectedTransactionIds` - Ids to patch (explicit mode). Ignored when `allSelected: true`.
        should("test selectedTransactionIds") {
            // uncomment below to test the property
            //modelInstance.selectedTransactionIds shouldBe ("TODO")
        }

        // to test the property `excludedTransactionIds` - Ids to skip (filter mode). Ignored when `allSelected: false`.
        should("test excludedTransactionIds") {
            // uncomment below to test the property
            //modelInstance.excludedTransactionIds shouldBe ("TODO")
        }

        // to test the property `allSelected` - Switch between explicit (false) and filter (true) selection.
        should("test allSelected") {
            // uncomment below to test the property
            //modelInstance.allSelected shouldBe ("TODO")
        }

        // to test the property `filters`
        should("test filters") {
            // uncomment below to test the property
            //modelInstance.filters shouldBe ("TODO")
        }

    }
}
