/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.CashflowSummary

class CashflowSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CashflowSummary
        //val modelInstance = CashflowSummary()

        // to test the property `sumIncome`
        should("test sumIncome") {
            // uncomment below to test the property
            //modelInstance.sumIncome shouldBe ("TODO")
        }

        // to test the property `sumExpense` - Signed (negative).
        should("test sumExpense") {
            // uncomment below to test the property
            //modelInstance.sumExpense shouldBe ("TODO")
        }

        // to test the property `savings`
        should("test savings") {
            // uncomment below to test the property
            //modelInstance.savings shouldBe ("TODO")
        }

        // to test the property `savingsRate`
        should("test savingsRate") {
            // uncomment below to test the property
            //modelInstance.savingsRate shouldBe ("TODO")
        }

    }
}
