/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.CostBasisLot

class CostBasisLotTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CostBasisLot
        //val modelInstance = CostBasisLot()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `acquisitionDate`
        should("test acquisitionDate") {
            // uncomment below to test the property
            //modelInstance.acquisitionDate shouldBe ("TODO")
        }

        // to test the property `quantity`
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `costBasis`
        should("test costBasis") {
            // uncomment below to test the property
            //modelInstance.costBasis shouldBe ("TODO")
        }

        // to test the property `currentValue`
        should("test currentValue") {
            // uncomment below to test the property
            //modelInstance.currentValue shouldBe ("TODO")
        }

        // to test the property `unrealizedGain`
        should("test unrealizedGain") {
            // uncomment below to test the property
            //modelInstance.unrealizedGain shouldBe ("TODO")
        }

    }
}
