/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.CreateManualAccountResponseData

class CreateManualAccountResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateManualAccountResponseData
        //val modelInstance = CreateManualAccountResponseData()

        // to test the property `accountId`
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

    }
}
