/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.CreatePaycheckResponseData
import com.nicholasklaene.monarchbridge.client.models.Paycheck

class CreatePaycheckResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreatePaycheckResponseData
        //val modelInstance = CreatePaycheckResponseData()

        // to test the property `paycheck`
        should("test paycheck") {
            // uncomment below to test the property
            //modelInstance.paycheck shouldBe ("TODO")
        }

    }
}
