/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.CreateCategoryResponseData
import com.nicholasklaene.monarchbridge.client.models.Category

class CreateCategoryResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateCategoryResponseData
        //val modelInstance = CreateCategoryResponseData()

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

    }
}
