/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.CredentialInstitutionRow

class CredentialInstitutionRowTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CredentialInstitutionRow
        //val modelInstance = CredentialInstitutionRow()

        // to test the property `credentialId`
        should("test credentialId") {
            // uncomment below to test the property
            //modelInstance.credentialId shouldBe ("TODO")
        }

        // to test the property `institutionId`
        should("test institutionId") {
            // uncomment below to test the property
            //modelInstance.institutionId shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `plaidInstitutionId`
        should("test plaidInstitutionId") {
            // uncomment below to test the property
            //modelInstance.plaidInstitutionId shouldBe ("TODO")
        }

        // to test the property `finicityInstitutionId`
        should("test finicityInstitutionId") {
            // uncomment below to test the property
            //modelInstance.finicityInstitutionId shouldBe ("TODO")
        }

        // to test the property `mxInstitutionId`
        should("test mxInstitutionId") {
            // uncomment below to test the property
            //modelInstance.mxInstitutionId shouldBe ("TODO")
        }

        // to test the property `preferredDataProvider`
        should("test preferredDataProvider") {
            // uncomment below to test the property
            //modelInstance.preferredDataProvider shouldBe ("TODO")
        }

        // to test the property `logo`
        should("test logo") {
            // uncomment below to test the property
            //modelInstance.logo shouldBe ("TODO")
        }

    }
}
