/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.DeleteTaxLotsBulkResponseData

class DeleteTaxLotsBulkResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeleteTaxLotsBulkResponseData
        //val modelInstance = DeleteTaxLotsBulkResponseData()

        // to test the property `deletedCount`
        should("test deletedCount") {
            // uncomment below to test the property
            //modelInstance.deletedCount shouldBe ("TODO")
        }

    }
}
