/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.GetAttachmentResponseData
import com.nicholasklaene.monarchbridge.client.models.AttachmentDetail

class GetAttachmentResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetAttachmentResponseData
        //val modelInstance = GetAttachmentResponseData()

        // to test the property `attachment`
        should("test attachment") {
            // uncomment below to test the property
            //modelInstance.attachment shouldBe ("TODO")
        }

    }
}
