/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.GetAuthStatusResponse

class GetAuthStatusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetAuthStatusResponse
        //val modelInstance = GetAuthStatusResponse()

        // to test the property `authenticated`
        should("test authenticated") {
            // uncomment below to test the property
            //modelInstance.authenticated shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `lastVerifiedAt`
        should("test lastVerifiedAt") {
            // uncomment below to test the property
            //modelInstance.lastVerifiedAt shouldBe ("TODO")
        }

    }
}
