/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.GetAppearanceResponseData
import com.nicholasklaene.monarchbridge.client.models.Appearance

class GetAppearanceResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetAppearanceResponseData
        //val modelInstance = GetAppearanceResponseData()

        // to test the property `appearance`
        should("test appearance") {
            // uncomment below to test the property
            //modelInstance.appearance shouldBe ("TODO")
        }

    }
}
