/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.GetBudgetTimelineResponseData
import com.nicholasklaene.monarchbridge.client.models.BudgetTimelineMonth

class GetBudgetTimelineResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetBudgetTimelineResponseData
        //val modelInstance = GetBudgetTimelineResponseData()

        // to test the property `months`
        should("test months") {
            // uncomment below to test the property
            //modelInstance.months shouldBe ("TODO")
        }

    }
}
