/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.GetRecurringDashboardResponseData
import com.nicholasklaene.monarchbridge.client.models.DashboardRecurringItem

class GetRecurringDashboardResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetRecurringDashboardResponseData
        //val modelInstance = GetRecurringDashboardResponseData()

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `remainingDueAmount`
        should("test remainingDueAmount") {
            // uncomment below to test the property
            //modelInstance.remainingDueAmount shouldBe ("TODO")
        }

    }
}
