/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.GetSpendingTrendsResponseData
import com.nicholasklaene.monarchbridge.client.models.SpendingTrends

class GetSpendingTrendsResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSpendingTrendsResponseData
        //val modelInstance = GetSpendingTrendsResponseData()

        // to test the property `trends`
        should("test trends") {
            // uncomment below to test the property
            //modelInstance.trends shouldBe ("TODO")
        }

    }
}
