/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.GetTopInstitutionGroupsResponseData
import com.nicholasklaene.monarchbridge.client.models.TopInstitutionGroup

class GetTopInstitutionGroupsResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTopInstitutionGroupsResponseData
        //val modelInstance = GetTopInstitutionGroupsResponseData()

        // to test the property `groups`
        should("test groups") {
            // uncomment below to test the property
            //modelInstance.groups shouldBe ("TODO")
        }

        // to test the property `equityAccountsCount`
        should("test equityAccountsCount") {
            // uncomment below to test the property
            //modelInstance.equityAccountsCount shouldBe ("TODO")
        }

        // to test the property `credentialsCount`
        should("test credentialsCount") {
            // uncomment below to test the property
            //modelInstance.credentialsCount shouldBe ("TODO")
        }

    }
}
