/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.GetZestimateResponseData
import com.nicholasklaene.monarchbridge.client.models.GetZestimateResponseDataZestimatesInner

class GetZestimateResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetZestimateResponseData
        //val modelInstance = GetZestimateResponseData()

        // to test the property `zestimates`
        should("test zestimates") {
            // uncomment below to test the property
            //modelInstance.zestimates shouldBe ("TODO")
        }

    }
}
