/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.GoalAllocationEntry

class GoalAllocationEntryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GoalAllocationEntry
        //val modelInstance = GoalAllocationEntry()

        // to test the property `goalId`
        should("test goalId") {
            // uncomment below to test the property
            //modelInstance.goalId shouldBe ("TODO")
        }

        // to test the property `accountId`
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `targetPercent`
        should("test targetPercent") {
            // uncomment below to test the property
            //modelInstance.targetPercent shouldBe ("TODO")
        }

    }
}
