/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.Holding

class HoldingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Holding
        //val modelInstance = Holding()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `ticker`
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `totalValue`
        should("test totalValue") {
            // uncomment below to test the property
            //modelInstance.totalValue shouldBe ("TODO")
        }

        // to test the property `totalQuantity`
        should("test totalQuantity") {
            // uncomment below to test the property
            //modelInstance.totalQuantity shouldBe ("TODO")
        }

        // to test the property `costBasis`
        should("test costBasis") {
            // uncomment below to test the property
            //modelInstance.costBasis shouldBe ("TODO")
        }

        // to test the property `lastPrice`
        should("test lastPrice") {
            // uncomment below to test the property
            //modelInstance.lastPrice shouldBe ("TODO")
        }

    }
}
