/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.LinkTransactionToGoalRequest

class LinkTransactionToGoalRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LinkTransactionToGoalRequest
        //val modelInstance = LinkTransactionToGoalRequest()

        // to test the property `goalId` - Target Monarch goal id.
        should("test goalId") {
            // uncomment below to test the property
            //modelInstance.goalId shouldBe ("TODO")
        }

    }
}
