/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.ListTransactionRulesResponseData
import com.nicholasklaene.monarchbridge.client.models.TransactionRule

class ListTransactionRulesResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListTransactionRulesResponseData
        //val modelInstance = ListTransactionRulesResponseData()

        // to test the property `rules`
        should("test rules") {
            // uncomment below to test the property
            //modelInstance.rules shouldBe ("TODO")
        }

    }
}
