/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.MerchantStats

class MerchantStatsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MerchantStats
        //val modelInstance = MerchantStats()

        // to test the property `merchantId`
        should("test merchantId") {
            // uncomment below to test the property
            //modelInstance.merchantId shouldBe ("TODO")
        }

        // to test the property `totalSpend`
        should("test totalSpend") {
            // uncomment below to test the property
            //modelInstance.totalSpend shouldBe ("TODO")
        }

        // to test the property `transactionCount`
        should("test transactionCount") {
            // uncomment below to test the property
            //modelInstance.transactionCount shouldBe ("TODO")
        }

        // to test the property `averageTransaction`
        should("test averageTransaction") {
            // uncomment below to test the property
            //modelInstance.averageTransaction shouldBe ("TODO")
        }

        // to test the property `firstSeen`
        should("test firstSeen") {
            // uncomment below to test the property
            //modelInstance.firstSeen shouldBe ("TODO")
        }

        // to test the property `lastSeen`
        should("test lastSeen") {
            // uncomment below to test the property
            //modelInstance.lastSeen shouldBe ("TODO")
        }

        // to test the property `monthsActive`
        should("test monthsActive") {
            // uncomment below to test the property
            //modelInstance.monthsActive shouldBe ("TODO")
        }

    }
}
