/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.PauseSubscriptionResponseData

class PauseSubscriptionResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PauseSubscriptionResponseData
        //val modelInstance = PauseSubscriptionResponseData()

        // to test the property `paused`
        should("test paused") {
            // uncomment below to test the property
            //modelInstance.paused shouldBe ("TODO")
        }

        // to test the property `pausedAt`
        should("test pausedAt") {
            // uncomment below to test the property
            //modelInstance.pausedAt shouldBe ("TODO")
        }

        // to test the property `resumeAt`
        should("test resumeAt") {
            // uncomment below to test the property
            //modelInstance.resumeAt shouldBe ("TODO")
        }

    }
}
