/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.PaycheckDepositInput

class PaycheckDepositInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaycheckDepositInput
        //val modelInstance = PaycheckDepositInput()

        // to test the property `transactionId`
        should("test transactionId") {
            // uncomment below to test the property
            //modelInstance.transactionId shouldBe ("TODO")
        }

    }
}
