/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.PreviewSubscriptionPlanChangeRequest

class PreviewSubscriptionPlanChangeRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PreviewSubscriptionPlanChangeRequest
        //val modelInstance = PreviewSubscriptionPlanChangeRequest()

        // to test the property `targetTier`
        should("test targetTier") {
            // uncomment below to test the property
            //modelInstance.targetTier shouldBe ("TODO")
        }

        // to test the property `billingFrequency` - Optional: 'monthly' or 'yearly'.
        should("test billingFrequency") {
            // uncomment below to test the property
            //modelInstance.billingFrequency shouldBe ("TODO")
        }

    }
}
