/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.StartDownloadTransactionsRequest

class StartDownloadTransactionsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StartDownloadTransactionsRequest
        //val modelInstance = StartDownloadTransactionsRequest()

        // to test the property `filters` - TransactionFilterInput - passed through verbatim. Common keys, `search`, `categories`, `accounts`, `tags`, `startDate`, `endDate`, `hideFromReports`.
        should("test filters") {
            // uncomment below to test the property
            //modelInstance.filters shouldBe ("TODO")
        }

        // to test the property `orderBy` - Sort key (e.g. `date` or `amount`). Optional.
        should("test orderBy") {
            // uncomment below to test the property
            //modelInstance.orderBy shouldBe ("TODO")
        }

    }
}
