/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.TopInstitutionGroup
import com.nicholasklaene.monarchbridge.client.models.TopInstitution

class TopInstitutionGroupTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TopInstitutionGroup
        //val modelInstance = TopInstitutionGroup()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `shortTitle`
        should("test shortTitle") {
            // uncomment below to test the property
            //modelInstance.shortTitle shouldBe ("TODO")
        }

        // to test the property `accountsConnectedCount`
        should("test accountsConnectedCount") {
            // uncomment below to test the property
            //modelInstance.accountsConnectedCount shouldBe ("TODO")
        }

        // to test the property `institutions`
        should("test institutions") {
            // uncomment below to test the property
            //modelInstance.institutions shouldBe ("TODO")
        }

    }
}
