/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.TransactionRuleAmountCriterion
import com.nicholasklaene.monarchbridge.client.models.TransactionRuleAmountRange

class TransactionRuleAmountCriterionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransactionRuleAmountCriterion
        //val modelInstance = TransactionRuleAmountCriterion()

        // to test the property ``operator`` - One of `equals`, `not_equals`, `greater_than`, `less_than`, `between`. Forwarded verbatim.
        should("test `operator`") {
            // uncomment below to test the property
            //modelInstance.`operator` shouldBe ("TODO")
        }

        // to test the property `isExpense` - When true, scope the comparison to expenses (negative amounts) only.
        should("test isExpense") {
            // uncomment below to test the property
            //modelInstance.isExpense shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `valueRange`
        should("test valueRange") {
            // uncomment below to test the property
            //modelInstance.valueRange shouldBe ("TODO")
        }

    }
}
