/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.TransactionsSummary

class TransactionsSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransactionsSummary
        //val modelInstance = TransactionsSummary()

        // to test the property `count`
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `sum`
        should("test sum") {
            // uncomment below to test the property
            //modelInstance.sum shouldBe ("TODO")
        }

        // to test the property `avg`
        should("test avg") {
            // uncomment below to test the property
            //modelInstance.avg shouldBe ("TODO")
        }

        // to test the property `min`
        should("test min") {
            // uncomment below to test the property
            //modelInstance.min shouldBe ("TODO")
        }

        // to test the property `max`
        should("test max") {
            // uncomment below to test the property
            //modelInstance.max shouldBe ("TODO")
        }

        // to test the property `first`
        should("test first") {
            // uncomment below to test the property
            //modelInstance.first shouldBe ("TODO")
        }

        // to test the property `last`
        should("test last") {
            // uncomment below to test the property
            //modelInstance.last shouldBe ("TODO")
        }

    }
}
