/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.UpdateHoldingRequest

class UpdateHoldingRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateHoldingRequest
        //val modelInstance = UpdateHoldingRequest()

        // to test the property `quantity`
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `securityType` - Monarch security type string (e.g. `equity`, `etf`, `cryptocurrency`).
        should("test securityType") {
            // uncomment below to test the property
            //modelInstance.securityType shouldBe ("TODO")
        }

        // to test the property `userCostBasis` - User-provided cost basis. Stored separately from the data-provider value.
        should("test userCostBasis") {
            // uncomment below to test the property
            //modelInstance.userCostBasis shouldBe ("TODO")
        }

    }
}
