/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.UpdateBudgetSettingsResponseData

class UpdateBudgetSettingsResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateBudgetSettingsResponseData
        //val modelInstance = UpdateBudgetSettingsResponseData()

        // to test the property `budgetSystem`
        should("test budgetSystem") {
            // uncomment below to test the property
            //modelInstance.budgetSystem shouldBe ("TODO")
        }

        // to test the property `budgetApplyToFutureMonthsDefault`
        should("test budgetApplyToFutureMonthsDefault") {
            // uncomment below to test the property
            //modelInstance.budgetApplyToFutureMonthsDefault shouldBe ("TODO")
        }

        // to test the property `budgetRolloverPeriodId`
        should("test budgetRolloverPeriodId") {
            // uncomment below to test the property
            //modelInstance.budgetRolloverPeriodId shouldBe ("TODO")
        }

        // to test the property `budgetRolloverPeriodStartMonth`
        should("test budgetRolloverPeriodStartMonth") {
            // uncomment below to test the property
            //modelInstance.budgetRolloverPeriodStartMonth shouldBe ("TODO")
        }

    }
}
