/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.UpdateFlexRolloverSettingsRequest

class UpdateFlexRolloverSettingsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateFlexRolloverSettingsRequest
        //val modelInstance = UpdateFlexRolloverSettingsRequest()

        // to test the property `rolloverStartMonth`
        should("test rolloverStartMonth") {
            // uncomment below to test the property
            //modelInstance.rolloverStartMonth shouldBe ("TODO")
        }

        // to test the property `rolloverStartingBalance`
        should("test rolloverStartingBalance") {
            // uncomment below to test the property
            //modelInstance.rolloverStartingBalance shouldBe ("TODO")
        }

        // to test the property `rolloverEnabled`
        should("test rolloverEnabled") {
            // uncomment below to test the property
            //modelInstance.rolloverEnabled shouldBe ("TODO")
        }

        // to test the property `budgetSystem`
        should("test budgetSystem") {
            // uncomment below to test the property
            //modelInstance.budgetSystem shouldBe ("TODO")
        }

    }
}
