/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.models.WithdrawFromGoalRequest

class WithdrawFromGoalRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WithdrawFromGoalRequest
        //val modelInstance = WithdrawFromGoalRequest()

        // to test the property `amount` - Dollar amount to withdraw (positive).
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `accountId` - Source account id (where the goal balance is parked).
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `date` - Withdrawal date. Defaults to today.
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

    }
}
