# coding: utf-8

"""
    Monarch Bridge

    HTTP/JSON wrapper over Monarch Money's GraphQL API.  **Contract conventions:** - Every successful 2xx body is `{\"data\": <typed object>}` (except `/healthz`   and `/v1/auth/{status,refresh}`, which return plain bodies so health probes   stay zero-parse). - Failure bodies, when returned, are `{\"code\": ..., \"message\": ..., \"details\": {...}}`. - Mutations whose application layer reports errors come back as `HTTP 422`   (the proxy walks Monarch's `data.<mutation>.errors[]` and surfaces it). - No per-request auth on the wire - the bridge holds Monarch's session token   itself, loaded once via the interactive bootstrap CLI.  **Source of truth.** This multi-file YAML tree is hand-curated and authoritative. Both request DTOs and response DTOs are generated from it via openapi-generator-gradle-plugin into `build/generated/openapi/`, along with a Spring `*Api` interface per tag that controllers implement directly. The spec drives the web layer end-to-end.  Full agent reference + every Monarch quirk: see `agents/context/AGENTS.md`. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monarch_bridge_client.models.get_transaction_split_templates_response import GetTransactionSplitTemplatesResponse

class TestGetTransactionSplitTemplatesResponse(unittest.TestCase):
    """GetTransactionSplitTemplatesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTransactionSplitTemplatesResponse:
        """Test GetTransactionSplitTemplatesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTransactionSplitTemplatesResponse`
        """
        model = GetTransactionSplitTemplatesResponse()
        if include_optional:
            return GetTransactionSplitTemplatesResponse(
                data = monarch_bridge_client.models.get_transaction_split_templates_response_data.getTransactionSplitTemplates_response_data(
                    templates = [
                        monarch_bridge_client.models.split_template.SplitTemplate(
                            id = '', 
                            name = '', 
                            splits = [
                                monarch_bridge_client.models.split_template_entry.SplitTemplateEntry(
                                    category_id = '', 
                                    category_name = '', 
                                    percent = 1.337, )
                                ], )
                        ], )
            )
        else:
            return GetTransactionSplitTemplatesResponse(
                data = monarch_bridge_client.models.get_transaction_split_templates_response_data.getTransactionSplitTemplates_response_data(
                    templates = [
                        monarch_bridge_client.models.split_template.SplitTemplate(
                            id = '', 
                            name = '', 
                            splits = [
                                monarch_bridge_client.models.split_template_entry.SplitTemplateEntry(
                                    category_id = '', 
                                    category_name = '', 
                                    percent = 1.337, )
                                ], )
                        ], ),
        )
        """

    def testGetTransactionSplitTemplatesResponse(self):
        """Test GetTransactionSplitTemplatesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
