# coding: utf-8

"""
    Monarch Bridge

    HTTP/JSON wrapper over Monarch Money's GraphQL API.  **Contract conventions:** - Every successful 2xx body is `{\"data\": <typed object>}` (except `/healthz`   and `/v1/auth/{status,refresh}`, which return plain bodies so health probes   stay zero-parse). - Failure bodies, when returned, are `{\"code\": ..., \"message\": ..., \"details\": {...}}`. - Mutations whose application layer reports errors come back as `HTTP 422`   (the proxy walks Monarch's `data.<mutation>.errors[]` and surfaces it). - No per-request auth on the wire - the bridge holds Monarch's session token   itself, loaded once via the interactive bootstrap CLI.  **Source of truth.** This multi-file YAML tree is hand-curated and authoritative. Both request DTOs and response DTOs are generated from it via openapi-generator-gradle-plugin into `build/generated/openapi/`, along with a Spring `*Api` interface per tag that controllers implement directly. The spec drives the web layer end-to-end.  Full agent reference + every Monarch quirk: see `agents/context/AGENTS.md`. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monarch_bridge_client.models.list_accounts_response import ListAccountsResponse

class TestListAccountsResponse(unittest.TestCase):
    """ListAccountsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAccountsResponse:
        """Test ListAccountsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAccountsResponse`
        """
        model = ListAccountsResponse()
        if include_optional:
            return ListAccountsResponse(
                data = monarch_bridge_client.models.list_accounts_response_data.listAccounts_response_data(
                    accounts = [
                        monarch_bridge_client.models.account.Account(
                            id = '', 
                            display_name = '', 
                            type = '', 
                            subtype = '', 
                            mask = '', 
                            current_balance = 1.337, 
                            display_balance = 1.337, 
                            is_hidden = True, 
                            hide_from_list = True, 
                            include_in_net_worth = True, 
                            is_asset = True, 
                            is_manual = True, 
                            institution = monarch_bridge_client.models.institution.Institution(
                                id = '', 
                                name = '', 
                                primary_color = '', 
                                url = '', 
                                plaid_institution_id = '', ), )
                        ], )
            )
        else:
            return ListAccountsResponse(
                data = monarch_bridge_client.models.list_accounts_response_data.listAccounts_response_data(
                    accounts = [
                        monarch_bridge_client.models.account.Account(
                            id = '', 
                            display_name = '', 
                            type = '', 
                            subtype = '', 
                            mask = '', 
                            current_balance = 1.337, 
                            display_balance = 1.337, 
                            is_hidden = True, 
                            hide_from_list = True, 
                            include_in_net_worth = True, 
                            is_asset = True, 
                            is_manual = True, 
                            institution = monarch_bridge_client.models.institution.Institution(
                                id = '', 
                                name = '', 
                                primary_color = '', 
                                url = '', 
                                plaid_institution_id = '', ), )
                        ], ),
        )
        """

    def testListAccountsResponse(self):
        """Test ListAccountsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
