# coding: utf-8

"""
    Monarch Bridge

    HTTP/JSON wrapper over Monarch Money's GraphQL API.  **Contract conventions:** - Every successful 2xx body is `{\"data\": <typed object>}` (except `/healthz`   and `/v1/auth/{status,refresh}`, which return plain bodies so health probes   stay zero-parse). - Failure bodies, when returned, are `{\"code\": ..., \"message\": ..., \"details\": {...}}`. - Mutations whose application layer reports errors come back as `HTTP 422`   (the proxy walks Monarch's `data.<mutation>.errors[]` and surfaces it). - No per-request auth on the wire - the bridge holds Monarch's session token   itself, loaded once via the interactive bootstrap CLI.  **Source of truth.** This multi-file YAML tree is hand-curated and authoritative. Both request DTOs and response DTOs are generated from it via openapi-generator-gradle-plugin into `build/generated/openapi/`, along with a Spring `*Api` interface per tag that controllers implement directly. The spec drives the web layer end-to-end.  Full agent reference + every Monarch quirk: see `agents/context/AGENTS.md`. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monarch_bridge_client.models.get_notifications_response_data import GetNotificationsResponseData

class TestGetNotificationsResponseData(unittest.TestCase):
    """GetNotificationsResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNotificationsResponseData:
        """Test GetNotificationsResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNotificationsResponseData`
        """
        model = GetNotificationsResponseData()
        if include_optional:
            return GetNotificationsResponseData(
                has_next_page = True,
                end_cursor = '',
                edges = [
                    monarch_bridge_client.models.get_notifications_response_data_edges_inner.getNotifications_response_data_edges_inner(
                        id = '', 
                        created_at = '', 
                        read_at = '', 
                        title = '', 
                        body = '', 
                        action = '', 
                        action_label = '', 
                        event_priority = '', 
                        is_pinned = True, 
                        logo = '', 
                        dismissed_at = '', 
                        event_type = '', 
                        secondary_url = '', )
                    ]
            )
        else:
            return GetNotificationsResponseData(
                edges = [
                    monarch_bridge_client.models.get_notifications_response_data_edges_inner.getNotifications_response_data_edges_inner(
                        id = '', 
                        created_at = '', 
                        read_at = '', 
                        title = '', 
                        body = '', 
                        action = '', 
                        action_label = '', 
                        event_priority = '', 
                        is_pinned = True, 
                        logo = '', 
                        dismissed_at = '', 
                        event_type = '', 
                        secondary_url = '', )
                    ],
        )
        """

    def testGetNotificationsResponseData(self):
        """Test GetNotificationsResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
