# coding: utf-8

"""
    Monarch Bridge

    HTTP/JSON wrapper over Monarch Money's GraphQL API.  **Contract conventions:** - Every successful 2xx body is `{\"data\": <typed object>}` (except `/healthz`   and `/v1/auth/{status,refresh}`, which return plain bodies so health probes   stay zero-parse). - Failure bodies, when returned, are `{\"code\": ..., \"message\": ..., \"details\": {...}}`. - Mutations whose application layer reports errors come back as `HTTP 422`   (the proxy walks Monarch's `data.<mutation>.errors[]` and surfaces it). - No per-request auth on the wire - the bridge holds Monarch's session token   itself, loaded once via the interactive bootstrap CLI.  **Source of truth.** This multi-file YAML tree is hand-curated and authoritative. Both request DTOs and response DTOs are generated from it via openapi-generator-gradle-plugin into `build/generated/openapi/`, along with a Spring `*Api` interface per tag that controllers implement directly. The spec drives the web layer end-to-end.  Full agent reference + every Monarch quirk: see `agents/context/AGENTS.md`. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from monarch_bridge_client.models.preview_transaction_rule_response_data import PreviewTransactionRuleResponseData

class TestPreviewTransactionRuleResponseData(unittest.TestCase):
    """PreviewTransactionRuleResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreviewTransactionRuleResponseData:
        """Test PreviewTransactionRuleResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreviewTransactionRuleResponseData`
        """
        model = PreviewTransactionRuleResponseData()
        if include_optional:
            return PreviewTransactionRuleResponseData(
                total_count = 56,
                results = [
                    monarch_bridge_client.models.transaction_rule_preview_match.TransactionRulePreviewMatch(
                        transaction = monarch_bridge_client.models.transaction.Transaction(
                            id = '', 
                            date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            amount = 1.337, 
                            pending = True, 
                            plaid_name = '', 
                            notes = '', 
                            hide_from_reports = True, 
                            needs_review = True, 
                            is_recurring = True, 
                            is_split_transaction = True, 
                            created_at = '', 
                            updated_at = '', 
                            account = monarch_bridge_client.models.transaction_account_ref.TransactionAccountRef(
                                id = '', 
                                display_name = '', ), 
                            merchant = monarch_bridge_client.models.merchant_ref.MerchantRef(
                                id = '', 
                                name = '', 
                                transactions_count = 56, ), 
                            category = monarch_bridge_client.models.ref.Ref(
                                id = '', 
                                name = '', ), 
                            tags = [
                                monarch_bridge_client.models.tag_ref.TagRef(
                                    id = '', 
                                    name = '', 
                                    color = '', 
                                    order = 56, )
                                ], ), 
                        new_name = '', 
                        new_split_transactions = [
                            { }
                            ], 
                        new_category = null, 
                        new_owner_is_joint = True, 
                        new_hide_from_reports = True, 
                        new_tags = [
                            monarch_bridge_client.models.ref.Ref(
                                id = '', 
                                name = '', )
                            ], 
                        new_goal = null, 
                        new_business_entity = null, 
                        new_business_entity_is_unassigned = True, )
                    ]
            )
        else:
            return PreviewTransactionRuleResponseData(
                total_count = 56,
                results = [
                    monarch_bridge_client.models.transaction_rule_preview_match.TransactionRulePreviewMatch(
                        transaction = monarch_bridge_client.models.transaction.Transaction(
                            id = '', 
                            date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            amount = 1.337, 
                            pending = True, 
                            plaid_name = '', 
                            notes = '', 
                            hide_from_reports = True, 
                            needs_review = True, 
                            is_recurring = True, 
                            is_split_transaction = True, 
                            created_at = '', 
                            updated_at = '', 
                            account = monarch_bridge_client.models.transaction_account_ref.TransactionAccountRef(
                                id = '', 
                                display_name = '', ), 
                            merchant = monarch_bridge_client.models.merchant_ref.MerchantRef(
                                id = '', 
                                name = '', 
                                transactions_count = 56, ), 
                            category = monarch_bridge_client.models.ref.Ref(
                                id = '', 
                                name = '', ), 
                            tags = [
                                monarch_bridge_client.models.tag_ref.TagRef(
                                    id = '', 
                                    name = '', 
                                    color = '', 
                                    order = 56, )
                                ], ), 
                        new_name = '', 
                        new_split_transactions = [
                            { }
                            ], 
                        new_category = null, 
                        new_owner_is_joint = True, 
                        new_hide_from_reports = True, 
                        new_tags = [
                            monarch_bridge_client.models.ref.Ref(
                                id = '', 
                                name = '', )
                            ], 
                        new_goal = null, 
                        new_business_entity = null, 
                        new_business_entity_is_unassigned = True, )
                    ],
        )
        """

    def testPreviewTransactionRuleResponseData(self):
        """Test PreviewTransactionRuleResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
