/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.nicholasklaene.monarchbridge.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.nicholasklaene.monarchbridge.client.apis.HoldingsApi
import com.nicholasklaene.monarchbridge.client.models.BulkUpdateHoldingsResponse
import com.nicholasklaene.monarchbridge.client.models.BulkUpdateHoldingsRequest
import com.nicholasklaene.monarchbridge.client.models.CreateManualAccountResponse
import com.nicholasklaene.monarchbridge.client.models.CreateManualHoldingResponse
import com.nicholasklaene.monarchbridge.client.models.CreateManualHoldingRequest
import com.nicholasklaene.monarchbridge.client.models.CreateManualInvestmentsAccountRequest
import com.nicholasklaene.monarchbridge.client.models.DeleteAccountResponse
import com.nicholasklaene.monarchbridge.client.models.GetHoldingHistoryResponse
import com.nicholasklaene.monarchbridge.client.models.GetHoldingTransactionsResponse
import com.nicholasklaene.monarchbridge.client.models.GetPortfolioAllocationResponse
import com.nicholasklaene.monarchbridge.client.models.GetPortfolioAllocationByHoldingsResponse
import com.nicholasklaene.monarchbridge.client.models.GetPortfolioAllocationHoldingsDetailResponse
import com.nicholasklaene.monarchbridge.client.models.GetSecurityDetailsResponse
import com.nicholasklaene.monarchbridge.client.models.GetSecurityDividendsResponse
import com.nicholasklaene.monarchbridge.client.models.GetSecurityHistoricalPerformanceResponse
import com.nicholasklaene.monarchbridge.client.models.RequestRefresh503Response
import com.nicholasklaene.monarchbridge.client.models.SearchSecuritiesResponse
import com.nicholasklaene.monarchbridge.client.models.UpdateHoldingResponse
import com.nicholasklaene.monarchbridge.client.models.UpdateHoldingRequest

class HoldingsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HoldingsApi
        //val apiInstance = HoldingsApi()

        // to test bulkUpdateHoldings
        should("test bulkUpdateHoldings") {
            // uncomment below to test bulkUpdateHoldings
            //val bulkUpdateHoldingsRequest : BulkUpdateHoldingsRequest =  // BulkUpdateHoldingsRequest | 
            //val result : BulkUpdateHoldingsResponse = apiInstance.bulkUpdateHoldings(bulkUpdateHoldingsRequest)
            //result shouldBe ("TODO")
        }

        // to test createManualHolding
        should("test createManualHolding") {
            // uncomment below to test createManualHolding
            //val id : kotlin.String = id_example // kotlin.String | Monarch account id.
            //val createManualHoldingRequest : CreateManualHoldingRequest =  // CreateManualHoldingRequest | 
            //val result : CreateManualHoldingResponse = apiInstance.createManualHolding(id, createManualHoldingRequest)
            //result shouldBe ("TODO")
        }

        // to test createManualInvestmentsAccount
        should("test createManualInvestmentsAccount") {
            // uncomment below to test createManualInvestmentsAccount
            //val createManualInvestmentsAccountRequest : CreateManualInvestmentsAccountRequest =  // CreateManualInvestmentsAccountRequest | 
            //val result : CreateManualAccountResponse = apiInstance.createManualInvestmentsAccount(createManualInvestmentsAccountRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteHolding
        should("test deleteHolding") {
            // uncomment below to test deleteHolding
            //val id : kotlin.String = id_example // kotlin.String | Monarch holding id.
            //val result : DeleteAccountResponse = apiInstance.deleteHolding(id)
            //result shouldBe ("TODO")
        }

        // to test getHoldingHistory
        should("test getHoldingHistory") {
            // uncomment below to test getHoldingHistory
            //val id : kotlin.String = id_example // kotlin.String | Monarch holding id.
            //val start : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | Lower bound (inclusive), `YYYY-MM-DD`.
            //val end : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | Upper bound (inclusive), `YYYY-MM-DD`.
            //val result : GetHoldingHistoryResponse = apiInstance.getHoldingHistory(id, start, end)
            //result shouldBe ("TODO")
        }

        // to test getHoldingTransactions
        should("test getHoldingTransactions") {
            // uncomment below to test getHoldingTransactions
            //val id : kotlin.String = id_example // kotlin.String | Monarch holding id.
            //val start : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | Lower bound (inclusive), `YYYY-MM-DD`.
            //val end : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | Upper bound (inclusive), `YYYY-MM-DD`.
            //val limit : kotlin.Int = 56 // kotlin.Int | Page size.
            //val offset : kotlin.Int = 56 // kotlin.Int | Page offset.
            //val result : GetHoldingTransactionsResponse = apiInstance.getHoldingTransactions(id, start, end, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test getPortfolioAllocation
        should("test getPortfolioAllocation") {
            // uncomment below to test getPortfolioAllocation
            //val accountIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Filter by one or more Monarch account ids. Repeat the query param for each. Preferred over the legacy single `accountId` param; both are accepted and merged. 
            //val classificationField : kotlin.String = classificationField_example // kotlin.String | Monarch's `PortfolioAllocationClassificationField` enum value (e.g. `SECURITY_TYPE`). Omit to use Monarch's default classification. 
            //val result : GetPortfolioAllocationResponse = apiInstance.getPortfolioAllocation(accountIds, classificationField)
            //result shouldBe ("TODO")
        }

        // to test getPortfolioAllocationByAccount
        should("test getPortfolioAllocationByAccount") {
            // uncomment below to test getPortfolioAllocationByAccount
            //val accountIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Filter by one or more Monarch account ids. Repeat the query param for each. Preferred over the legacy single `accountId` param; both are accepted and merged. 
            //val limit : kotlin.Int = 56 // kotlin.Int | Page size.
            //val result : GetPortfolioAllocationByHoldingsResponse = apiInstance.getPortfolioAllocationByAccount(accountIds, limit)
            //result shouldBe ("TODO")
        }

        // to test getPortfolioAllocationByHoldings
        should("test getPortfolioAllocationByHoldings") {
            // uncomment below to test getPortfolioAllocationByHoldings
            //val accountIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Filter by one or more Monarch account ids. Repeat the query param for each. Preferred over the legacy single `accountId` param; both are accepted and merged. 
            //val limit : kotlin.Int = 56 // kotlin.Int | Page size.
            //val result : GetPortfolioAllocationByHoldingsResponse = apiInstance.getPortfolioAllocationByHoldings(accountIds, limit)
            //result shouldBe ("TODO")
        }

        // to test getPortfolioAllocationHoldingsDetail
        should("test getPortfolioAllocationHoldingsDetail") {
            // uncomment below to test getPortfolioAllocationHoldingsDetail
            //val classificationField : kotlin.String = classificationField_example // kotlin.String | Monarch's `PortfolioAllocationClassificationField` enum value.
            //val classificationValue : kotlin.String = classificationValue_example // kotlin.String | The specific bucket value within `classificationField` to drill into.
            //val accountIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Filter by one or more Monarch account ids. Repeat the query param for each. Preferred over the legacy single `accountId` param; both are accepted and merged. 
            //val limit : kotlin.Int = 56 // kotlin.Int | Page size.
            //val offset : kotlin.Int = 56 // kotlin.Int | Page offset.
            //val result : GetPortfolioAllocationHoldingsDetailResponse = apiInstance.getPortfolioAllocationHoldingsDetail(classificationField, classificationValue, accountIds, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test getSecurityDetails
        should("test getSecurityDetails") {
            // uncomment below to test getSecurityDetails
            //val id : kotlin.String = id_example // kotlin.String | Monarch security id.
            //val result : GetSecurityDetailsResponse = apiInstance.getSecurityDetails(id)
            //result shouldBe ("TODO")
        }

        // to test getSecurityDividends
        should("test getSecurityDividends") {
            // uncomment below to test getSecurityDividends
            //val id : kotlin.String = id_example // kotlin.String | Monarch security id.
            //val start : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | Lower bound (inclusive), `YYYY-MM-DD`.
            //val end : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | Upper bound (inclusive), `YYYY-MM-DD`.
            //val result : GetSecurityDividendsResponse = apiInstance.getSecurityDividends(id, start, end)
            //result shouldBe ("TODO")
        }

        // to test getSecurityHistoricalPerformance
        should("test getSecurityHistoricalPerformance") {
            // uncomment below to test getSecurityHistoricalPerformance
            //val id : kotlin.String = id_example // kotlin.String | Monarch security id.
            //val start : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | Window start (inclusive).
            //val end : java.time.LocalDate = 2013-10-20 // java.time.LocalDate | Window end (inclusive).
            //val result : GetSecurityHistoricalPerformanceResponse = apiInstance.getSecurityHistoricalPerformance(id, start, end)
            //result shouldBe ("TODO")
        }

        // to test searchSecurities
        should("test searchSecurities") {
            // uncomment below to test searchSecurities
            //val q : kotlin.String = q_example // kotlin.String | Search text (ticker, name, partial match).
            //val limit : kotlin.Int = 56 // kotlin.Int | Cap the result count. Monarch defaults to a small page when omitted.
            //val orderByPopularity : kotlin.Boolean = true // kotlin.Boolean | When true, Monarch ranks by popularity instead of relevance.
            //val result : SearchSecuritiesResponse = apiInstance.searchSecurities(q, limit, orderByPopularity)
            //result shouldBe ("TODO")
        }

        // to test updateHolding
        should("test updateHolding") {
            // uncomment below to test updateHolding
            //val id : kotlin.String = id_example // kotlin.String | Monarch holding id.
            //val updateHoldingRequest : UpdateHoldingRequest =  // UpdateHoldingRequest | 
            //val result : UpdateHoldingResponse = apiInstance.updateHolding(id, updateHoldingRequest)
            //result shouldBe ("TODO")
        }

    }
}
